-- Longe & Perto — cartas padrão do jogo. Rode DEPOIS do 002_cartas.sql.
-- Pode rodar de novo: cartas que já existem são ignoradas (on conflict do nothing).

-- verdade · leve (40)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('verdade', 'leve', 'Qual foi a primeira coisa que você reparou em mim?', null),
  ('verdade', 'leve', 'Qual momento nosso você reviveria se pudesse?', null),
  ('verdade', 'leve', 'O que você faz quando está com saudade de mim?', null),
  ('verdade', 'leve', 'Qual mania minha você acha mais fofa?', null),
  ('verdade', 'leve', 'Qual mania minha te irrita um pouquinho?', null),
  ('verdade', 'leve', 'Qual mensagem minha mais te marcou até hoje?', null),
  ('verdade', 'leve', 'Se a gente tivesse um dia juntos amanhã, o que faríamos?', null),
  ('verdade', 'leve', 'Qual música te faz pensar em mim?', null),
  ('verdade', 'leve', 'Qual foi a vez que você mais sentiu ciúme de mim?', null),
  ('verdade', 'leve', 'O que você ainda não me contou sobre a sua infância?', null),
  ('verdade', 'leve', 'Qual apelido meu você mais gosta?', null),
  ('verdade', 'leve', 'Qual foi o seu maior mico na frente de alguém que você gostava?', null),
  ('verdade', 'leve', 'Qual lugar você mais quer conhecer comigo?', null),
  ('verdade', 'leve', 'Em que momento você percebeu que gostava de mim?', null),
  ('verdade', 'leve', 'Qual comida você quer que a gente coma junto no reencontro?', null),
  ('verdade', 'leve', 'Qual foi o dia mais difícil da distância para você?', null),
  ('verdade', 'leve', 'Qual defeito seu você acha que eu nem percebi?', null),
  ('verdade', 'leve', 'Como você imagina a nossa vida daqui a 5 anos?', null),
  ('verdade', 'leve', 'Qual foi a última vez que você chorou, e por quê?', null),
  ('verdade', 'leve', 'O que eu faço que te deixa com o dia melhor?', null),
  ('verdade', 'leve', 'Qual foi o seu pior encontro antes de mim?', null),
  ('verdade', 'leve', 'Qual é a coisa mais boba que te deixa feliz?', null),
  ('verdade', 'leve', 'O que você pensou de mim na nossa primeira conversa?', null),
  ('verdade', 'leve', 'Qual hábito meu você pegou sem perceber?', null),
  ('verdade', 'leve', 'Qual foi a última coisa que você pesquisou no Google?', null),
  ('verdade', 'leve', 'Qual presente meu você guarda com mais carinho?', null),
  ('verdade', 'leve', 'Se pudesse mudar uma coisa na nossa rotina a distância, o que seria?', null),
  ('verdade', 'leve', 'Qual foi a última mentirinha que você me contou?', null),
  ('verdade', 'leve', 'Qual é o seu maior medo sobre a distância?', null),
  ('verdade', 'leve', 'Qual série você quer que a gente assista junto?', null),
  ('verdade', 'leve', 'Qual foi o momento em que você mais riu comigo?', null),
  ('verdade', 'leve', 'Quem da sua família mais pergunta de mim?', null),
  ('verdade', 'leve', 'Qual é a sua lembrança favorita da infância?', null),
  ('verdade', 'leve', 'O que você faria com um dia inteiro só para você?', null),
  ('verdade', 'leve', 'Qual foi a última vez que você sentiu orgulho de mim?', null),
  ('verdade', 'leve', 'Qual foto nossa é a sua favorita?', null),
  ('verdade', 'leve', 'O que você mais gosta na sua própria personalidade?', null),
  ('verdade', 'leve', 'Qual comida você não comeria nem por amor?', null),
  ('verdade', 'leve', 'Qual sonho você ainda não me contou?', null),
  ('verdade', 'leve', 'Qual foi a coisa mais corajosa que você já fez?', null)
on conflict do nothing;

-- verdade · criativo (26)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('verdade', 'criativo', 'Se o nosso namoro fosse um filme, qual seria o título?', null),
  ('verdade', 'criativo', 'Se eu fosse um animal, qual eu seria, e por quê?', null),
  ('verdade', 'criativo', 'Que superpoder você usaria para chegar até mim agora?', null),
  ('verdade', 'criativo', 'Descreva o nosso casal usando só 3 emojis.', null),
  ('verdade', 'criativo', 'Se a gente tivesse uma banda, qual seria o nome e o estilo?', null),
  ('verdade', 'criativo', 'Qual personagem de série mais parece comigo?', null),
  ('verdade', 'criativo', 'Se a gente fosse personagens de um jogo, quais seriam os nossos poderes?', null),
  ('verdade', 'criativo', 'Qual seria o nome do nosso livro de memórias?', null),
  ('verdade', 'criativo', 'Se o nosso namoro tivesse uma trilha sonora, qual seria a primeira música?', null),
  ('verdade', 'criativo', 'Que invenção você criaria para acabar com a distância?', null),
  ('verdade', 'criativo', 'Se eu fosse uma comida, qual seria?', null),
  ('verdade', 'criativo', 'Como seria o nosso casamento com orçamento infinito?', null),
  ('verdade', 'criativo', 'Qual seria o nome do nosso pet imaginário?', null),
  ('verdade', 'criativo', 'Se a gente abrisse um negócio juntos, o que seria?', null),
  ('verdade', 'criativo', 'Em qual época da história você gostaria de viver comigo?', null),
  ('verdade', 'criativo', 'Qual seria a minha profissão num universo paralelo?', null),
  ('verdade', 'criativo', 'Se a nossa história virasse novela, quem faria o vilão?', null),
  ('verdade', 'criativo', 'Que cor você acha que eu sou, e por quê?', null),
  ('verdade', 'criativo', 'Qual final de filme você mudaria para ser sobre nós?', null),
  ('verdade', 'criativo', 'Qual lenda ou mito combina com o nosso namoro?', null),
  ('verdade', 'criativo', 'Qual seria o feriado nacional do nosso casal?', null),
  ('verdade', 'criativo', 'Se a gente entrasse num reality show, qual seria a nossa estratégia?', null),
  ('verdade', 'criativo', 'Descreva o nosso futuro numa frase de biscoito da sorte.', null),
  ('verdade', 'criativo', 'Se você criasse uma lei para casais a distância, qual seria?', null),
  ('verdade', 'criativo', 'Qual objeto da sua casa melhor representa o nosso namoro?', null),
  ('verdade', 'criativo', 'Se a gente fosse uma dupla de detetives, qual seria o nosso primeiro caso?', null)
on conflict do nothing;

-- verdade · picante (35)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('verdade', 'picante', 'Em que momento você mais sentiu vontade de me beijar?', null),
  ('verdade', 'picante', 'O que em mim mais te provoca?', null),
  ('verdade', 'picante', 'Qual roupa minha você mais gosta de me ver usando?', null),
  ('verdade', 'picante', 'Já pensou em mim num momento totalmente inapropriado? Qual?', null),
  ('verdade', 'picante', 'Onde você mais gostaria de me beijar agora?', null),
  ('verdade', 'picante', 'Qual foi o nosso momento mais quente até hoje?', null),
  ('verdade', 'picante', 'Qual mensagem minha mais te deixou mexido(a)?', null),
  ('verdade', 'picante', 'Qual parte do reencontro você mais imagina?', null),
  ('verdade', 'picante', 'O que você gostaria que eu fizesse mais vezes?', null),
  ('verdade', 'picante', 'Qual é a sua fantasia mais leve comigo?', null),
  ('verdade', 'picante', 'O que você mais gosta de sentir quando a gente se beija?', null),
  ('verdade', 'picante', 'Qual foi a primeira vez que você me achou irresistível?', null),
  ('verdade', 'picante', 'Que tipo de mensagem minha mais te provoca?', null),
  ('verdade', 'picante', 'Qual cheiro meu você mais sente falta?', null),
  ('verdade', 'picante', 'Qual é a parte do seu corpo que você mais gosta?', null),
  ('verdade', 'picante', 'O que você vestiria para me receber no reencontro?', null),
  ('verdade', 'picante', 'Em qual lugar inusitado você já imaginou a gente se beijando?', null),
  ('verdade', 'picante', 'Qual foi o sonho mais quente que você já teve comigo?', null),
  ('verdade', 'picante', 'O que eu faço sem perceber que te deixa com vontade?', null),
  ('verdade', 'picante', 'Você prefere ser provocado(a) devagar ou ir direto ao ponto?', null),
  ('verdade', 'picante', 'Qual música te deixa no clima pensando em mim?', null),
  ('verdade', 'picante', 'Que elogio sobre o seu corpo você mais gosta de ouvir?', null),
  ('verdade', 'picante', 'Qual foto minha mais mexeu com você?', null),
  ('verdade', 'picante', 'O que você nunca teve coragem de me pedir?', null),
  ('verdade', 'picante', 'Qual é a sua lingerie ou cueca favorita?', null),
  ('verdade', 'picante', 'Você já se arrumou só para me provocar numa chamada?', null),
  ('verdade', 'picante', 'Qual roupa você gostaria que eu usasse na nossa próxima chamada?', null),
  ('verdade', 'picante', 'De 0 a 10, quanta saudade física você está sentindo agora?', null),
  ('verdade', 'picante', 'Onde você mais gosta de receber carinho?', null),
  ('verdade', 'picante', 'Qual foi a mensagem mais ousada que você quase me mandou?', null),
  ('verdade', 'picante', 'Qual é a sua posição favorita comigo?', null),
  ('verdade', 'picante', 'Qual posição você tem curiosidade de experimentar?', null),
  ('verdade', 'picante', 'Qual posição te lembra a nossa melhor noite?', null),
  ('verdade', 'picante', 'Você prefere estar no controle ou deixar eu conduzir?', null),
  ('verdade', 'picante', 'Qual posição você acha que eu mais gosto?', null)
on conflict do nothing;

-- verdade · pesado (30)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('verdade', 'pesado', 'Qual fantasia você tem vergonha de me contar?', null),
  ('verdade', 'pesado', 'Qual foi o pensamento mais ousado que você já teve comigo?', null),
  ('verdade', 'pesado', 'O que você nunca fez e gostaria de experimentar comigo?', null),
  ('verdade', 'pesado', 'Qual limite seu eu ainda não conheço?', null),
  ('verdade', 'pesado', 'Como seria o nosso reencontro, sem cortes?', null),
  ('verdade', 'pesado', 'Qual é a fantasia que você mais quer realizar comigo?', null),
  ('verdade', 'pesado', 'Qual foi a nossa noite mais intensa até hoje?', null),
  ('verdade', 'pesado', 'O que você já fez pensando em mim quando estava sozinho(a)?', null),
  ('verdade', 'pesado', 'O que você quer experimentar comigo e ainda não pediu?', null),
  ('verdade', 'pesado', 'Onde você gostaria que a gente estivesse agora, sem ninguém por perto?', null),
  ('verdade', 'pesado', 'Que foto minha você gostaria de receber hoje?', null),
  ('verdade', 'pesado', 'Qual é o seu maior "sim" e o seu maior "não" na intimidade?', null),
  ('verdade', 'pesado', 'Qual cena de filme ou série te deixou pensando em nós?', null),
  ('verdade', 'pesado', 'Você prefere mandar ou receber nudes? Por quê?', null),
  ('verdade', 'pesado', 'Qual foi o momento em que você mais me quis e não podia?', null),
  ('verdade', 'pesado', 'Qual palavra minha mais te deixa no clima?', null),
  ('verdade', 'pesado', 'Qual é a sua fantasia com chamada de vídeo?', null),
  ('verdade', 'pesado', 'O que você quer que eu vista quando a gente se reencontrar?', null),
  ('verdade', 'pesado', 'Qual parte do meu corpo você mais queria ver agora?', null),
  ('verdade', 'pesado', 'Você já me imaginou numa situação ousada em público? Conta.', null),
  ('verdade', 'pesado', 'O que você faria comigo com uma hora livre e nenhuma regra?', null),
  ('verdade', 'pesado', 'Qual foi a coisa mais ousada que você já fez num relacionamento?', null),
  ('verdade', 'pesado', 'Como você gostaria de ser acordado(a) por mim?', null),
  ('verdade', 'pesado', 'Qual fantasia você acha que eu tenho e não conto?', null),
  ('verdade', 'pesado', 'Que regra você criaria para as nossas chamadas mais quentes?', null),
  ('verdade', 'pesado', 'Qual posição te faz perder o controle?', null),
  ('verdade', 'pesado', 'Qual posição você nunca fez e morre de vontade de fazer?', null),
  ('verdade', 'pesado', 'Qual posição você mais imagina quando pensa em mim?', null),
  ('verdade', 'pesado', 'Qual posição você achava que não ia gostar e acabou gostando?', null),
  ('verdade', 'pesado', 'Qual posição você quer que seja a primeira no reencontro?', null)
on conflict do nothing;

-- desafio · leve (70)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('desafio', 'leve', 'Faça 10 polichinelos cantando a nossa música.', null),
  ('desafio', 'leve', 'Desenhe meu retrato em 60 segundos e mostre na câmera.', null),
  ('desafio', 'leve', 'Imite meu jeito de falar quando acabo de acordar.', null),
  ('desafio', 'leve', 'Invente uma história de 1 minuto usando 3 objetos que estão perto de você.', null),
  ('desafio', 'leve', 'Dance por 15 segundos a música que eu escolher.', null),
  ('desafio', 'leve', 'Faça um desfile de moda com 3 peças aleatórias do seu guarda-roupa.', null),
  ('desafio', 'leve', 'Monte um look usando só coisas da cozinha.', null),
  ('desafio', 'leve', 'Imite um apresentador de jornal anunciando uma notícia sobre nós dois.', null),
  ('desafio', 'leve', 'Faça a pior careta que conseguir e segure 10 segundos sem rir.', null),
  ('desafio', 'leve', 'Cante o refrão de uma música trocando a letra por palavras sobre mim.', null),
  ('desafio', 'leve', 'Faça a pose de estátua que eu escolher e fique parado(a) 30 segundos.', null),
  ('desafio', 'leve', 'Desenhe o nosso próximo encontro em 2 minutos.', null),
  ('desafio', 'leve', 'Mostre o objeto mais estranho do seu quarto e invente a história dele.', null),
  ('desafio', 'leve', 'Leia algo que estiver perto de você com voz de narrador de novela.', null),
  ('desafio', 'leve', 'Faça um comercial de 30 segundos vendendo um item do seu quarto.', null),
  ('desafio', 'leve', 'Imite um animal até eu adivinhar qual é.', null),
  ('desafio', 'leve', 'Faça mímica de um filme até eu acertar.', null),
  ('desafio', 'leve', 'Escreva um poema de 4 versos sobre mim em 2 minutos e leia.', null),
  ('desafio', 'leve', 'Faça 10 agachamentos mandando um beijo a cada um.', null),
  ('desafio', 'leve', 'Equilibre um objeto na cabeça e atravesse o cômodo.', null),
  ('desafio', 'leve', 'Fale por 1 minuto sobre o seu dia sem dizer a palavra "não".', null),
  ('desafio', 'leve', 'Desenhe com a mão não dominante o bicho que eu escolher.', null),
  ('desafio', 'leve', 'Faça um tour pelo seu quarto como se fosse guia de museu.', null),
  ('desafio', 'leve', 'Imite um professor dando uma aula sobre mim.', null),
  ('desafio', 'leve', 'Faça beatbox por 20 segundos.', null),
  ('desafio', 'leve', 'Conte a piada mais ruim que souber com a cara totalmente séria.', null),
  ('desafio', 'leve', 'Faça um penteado maluco em 1 minuto.', null),
  ('desafio', 'leve', 'Crie um personagem com o que tiver no quarto e fale como ele por 1 minuto.', null),
  ('desafio', 'leve', 'Vamos criar um aperto de mão secreto nosso pela câmera.', null),
  ('desafio', 'leve', 'Faça sua melhor pose de capa de revista (eu tiro print).', null),
  ('desafio', 'leve', 'Faça um aviãozinho de papel e lance o mais longe que conseguir.', null),
  ('desafio', 'leve', 'Escreva meu nome no ar usando o corpo inteiro.', null),
  ('desafio', 'leve', 'Recrie um meme famoso.', null),
  ('desafio', 'leve', 'Recrie a nossa primeira foto juntos, só que sozinho(a).', null),
  ('desafio', 'leve', 'Diga 5 coisas que você ama em mim em 20 segundos.', null),
  ('desafio', 'leve', 'Fale com o sotaque de outro estado pelas próximas 2 rodadas.', null),
  ('desafio', 'leve', 'Duble uma cena de filme que eu colocar sem som.', null),
  ('desafio', 'leve', 'Desenhe como você imagina a nossa casa no futuro.', null),
  ('desafio', 'leve', 'Faça prancha por 30 segundos enquanto responde uma pergunta minha.', null),
  ('desafio', 'leve', 'Imite uma celebridade até eu adivinhar quem é.', null),
  ('desafio', 'leve', 'Ache em 30 segundos um objeto de cada cor que eu disser.', null),
  ('desafio', 'leve', 'Toque uma música com um instrumento improvisado (panela, copo, caneta).', null),
  ('desafio', 'leve', 'Faça um rap de 4 versos sobre o seu dia.', null),
  ('desafio', 'leve', 'Narre o que vai fazer amanhã como narrador de futebol.', null),
  ('desafio', 'leve', 'Escreva uma carta de amor de 3 linhas como se estivéssemos em 1800.', null),
  ('desafio', 'leve', 'Responda as próximas 3 perguntas só cantando.', null),
  ('desafio', 'leve', 'Desenhe um mapa do tesouro da sua casa e explique onde está o tesouro.', null),
  ('desafio', 'leve', 'Adivinhe 3 coisas que estão na minha mesa agora.', null),
  ('desafio', 'leve', 'Faça uma declaração de amor dramática estilo novela mexicana.', null),
  ('desafio', 'leve', 'Mande uma selfie agora, do jeito que você estiver, sem se arrumar.', 'foto'),
  ('desafio', 'leve', 'Mostre o que tem na sua geladeira e comente como um crítico gastronômico.', null),
  ('desafio', 'leve', 'Faça 15 segundos de dança robótica.', null),
  ('desafio', 'leve', 'Fale um trava-língua 3 vezes seguidas sem errar.', null),
  ('desafio', 'leve', 'Mostre sua caneca ou copo favorito e conte a história dele.', null),
  ('desafio', 'leve', 'Finja ser atendente de telemarketing tentando me vender você mesmo(a).', null),
  ('desafio', 'leve', 'Mande um áudio de bom dia para eu ouvir amanhã cedo.', 'audio'),
  ('desafio', 'leve', 'Pule corda imaginária por 20 segundos.', null),
  ('desafio', 'leve', 'Mostre a sua meia mais feia.', null),
  ('desafio', 'leve', 'Imite o som de 3 animais sem pausa.', null),
  ('desafio', 'leve', 'Faça uma pose de super-herói e diga o seu slogan.', null),
  ('desafio', 'leve', 'Faça um coração com as mãos e segure até eu dizer chega.', null),
  ('desafio', 'leve', 'Vista uma camiseta do avesso e fique assim até a próxima rodada.', null),
  ('desafio', 'leve', 'Conte até 10 em outra língua.', null),
  ('desafio', 'leve', 'Tente equilibrar uma colher no nariz.', null),
  ('desafio', 'leve', 'Mande uma selfie imitando a minha cara favorita.', 'foto'),
  ('desafio', 'leve', 'Mostre a vista da sua janela e descreva como um corretor de imóveis.', null),
  ('desafio', 'leve', 'Me faça 3 elogios com voz de robô.', null),
  ('desafio', 'leve', 'Massageie as próprias mãos narrando como se fosse um spa de luxo.', null),
  ('desafio', 'leve', 'Me mostre o seu cantinho favorito da casa.', null),
  ('desafio', 'leve', 'Fale por 30 segundos sobre o seu dia usando só palavras com mais de 3 letras.', null)
on conflict do nothing;

-- desafio · criativo (50)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('desafio', 'criativo', 'Invente o trailer de 1 minuto de um filme sobre nós dois.', null),
  ('desafio', 'criativo', 'Crie um nome e um logo para o nosso casal e desenhe.', null),
  ('desafio', 'criativo', 'Narre como seria o nosso encontro perfeito no estilo documentário de natureza.', null),
  ('desafio', 'criativo', 'Escreva uma música de 4 versos na melodia de "Parabéns a você".', null),
  ('desafio', 'criativo', 'Invente uma receita com 3 ingredientes da sua geladeira e apresente como chef de TV.', null),
  ('desafio', 'criativo', 'Me desenhe como herói ou heroína de desenho animado.', null),
  ('desafio', 'criativo', 'Crie uma coreografia de 20 segundos que eu tenho que copiar.', null),
  ('desafio', 'criativo', 'Faça teatro de sombras com as mãos e conte uma história curta.', null),
  ('desafio', 'criativo', 'Invente uma palavra nova e diga o que ela significa para nós.', null),
  ('desafio', 'criativo', 'Escreva um haicai (3 versos curtos) sobre saudade.', null),
  ('desafio', 'criativo', 'Me entreviste como se eu fosse uma pessoa famosa.', null),
  ('desafio', 'criativo', 'Monte uma cena com objetos da casa e narre o que está acontecendo.', null),
  ('desafio', 'criativo', 'Recrie a capa de um álbum ou filme famoso usando coisas de casa.', null),
  ('desafio', 'criativo', 'Imite como eu fico quando estou com fome.', null),
  ('desafio', 'criativo', 'Invente o meu horóscopo de hoje.', null),
  ('desafio', 'criativo', 'História a dois: cada um fala uma frase, por 10 rodadas.', null),
  ('desafio', 'criativo', 'Desenhe de olhos fechados o que eu descrever.', null),
  ('desafio', 'criativo', 'Faça um unboxing dramático de um objeto qualquer.', null),
  ('desafio', 'criativo', 'Faça um cartaz de procura-se com meu retrato falado e uma recompensa.', null),
  ('desafio', 'criativo', 'Apresente o nosso próximo encontro em 1 minuto como se fosse agente de viagens.', null),
  ('desafio', 'criativo', 'Treino juntos: 1 minuto de exercícios que eu vou comandando.', null),
  ('desafio', 'criativo', 'Espelho: imite todos os meus movimentos por 30 segundos.', null),
  ('desafio', 'criativo', 'Fique numa perna só de olhos fechados o máximo que conseguir.', null),
  ('desafio', 'criativo', 'Faça 3 posições de ioga que eu escolher.', null),
  ('desafio', 'criativo', 'Pedra, papel e tesoura, melhor de 5: quem perde cumpre um desafio extra.', null),
  ('desafio', 'criativo', 'Tente encostar a língua no nariz.', null),
  ('desafio', 'criativo', 'Monte a torre mais alta que conseguir com objetos em 1 minuto.', null),
  ('desafio', 'criativo', 'Corrida: traga primeiro para a câmera o objeto que eu disser.', null),
  ('desafio', 'criativo', 'Encene uma cena de filme romântico sozinho(a), fazendo as duas vozes.', null),
  ('desafio', 'criativo', 'Desenhe um presente que você gostaria de me dar.', null),
  ('desafio', 'criativo', 'Faça uma escultura com massinha, papel ou comida que me represente.', null),
  ('desafio', 'criativo', 'Invente um jingle de 15 segundos para o nosso casal.', null),
  ('desafio', 'criativo', 'Conte como a gente se conheceu no estilo conto de fadas.', null),
  ('desafio', 'criativo', 'Desenhe o caminho da sua casa até a minha, com monstros no meio.', null),
  ('desafio', 'criativo', 'Faça um fantoche de meia e faça ele me pedir em namoro de novo.', null),
  ('desafio', 'criativo', 'Faça um poema em que cada verso começa com uma letra do meu nome.', null),
  ('desafio', 'criativo', 'Grave um áudio narrando o seu dia como documentário.', 'audio'),
  ('desafio', 'criativo', 'Desenhe o nosso futuro pet e dê um nome para ele.', null),
  ('desafio', 'criativo', 'Faça um desfile com o tema que eu escolher.', null),
  ('desafio', 'criativo', 'Invente uma poção do amor com o que tiver na cozinha e mostre o preparo.', null),
  ('desafio', 'criativo', 'Encene o nosso reencontro usando objetos como personagens.', null),
  ('desafio', 'criativo', 'Escreva a manchete de jornal sobre nós daqui a 10 anos.', null),
  ('desafio', 'criativo', 'Faça uma paródia de 4 versos de uma música famosa sobre a nossa distância.', null),
  ('desafio', 'criativo', 'Desenhe como seria a nossa casa na árvore.', null),
  ('desafio', 'criativo', 'Crie uma coreografia só com as mãos.', null),
  ('desafio', 'criativo', 'Imite uma cena de filme de ação usando só coisas do quarto.', null),
  ('desafio', 'criativo', 'Invente um idioma de 5 palavras só nosso e me ensine.', null),
  ('desafio', 'criativo', 'Conte uma história de terror de 1 minuto com final romântico.', null),
  ('desafio', 'criativo', 'Faça um cartão de aniversário para mim só com o que estiver na sua mesa.', null),
  ('desafio', 'criativo', 'Tire uma foto artística de um objeto qualquer e me mande com um título.', 'foto')
on conflict do nothing;

-- desafio · picante (45)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('desafio', 'picante', 'Diga sussurrando o que você faria se eu estivesse aí agora.', null),
  ('desafio', 'picante', 'Mande um áudio de 20 segundos com a sua voz mais sedutora.', 'audio'),
  ('desafio', 'picante', 'Faça uma dança sensual de 20 segundos na música que eu escolher.', null),
  ('desafio', 'picante', 'Descreva o nosso melhor beijo com detalhes.', null),
  ('desafio', 'picante', 'Mostre a peça de roupa que você acha que mais me provoca.', null),
  ('desafio', 'picante', 'Tire uma foto sensual (você decide o nível) e me mande.', 'foto'),
  ('desafio', 'picante', 'Conte uma fantasia leve que você nunca me contou.', null),
  ('desafio', 'picante', 'Beije a câmera como se fosse eu.', null),
  ('desafio', 'picante', 'Faça um desfile com a roupa que eu escolher.', null),
  ('desafio', 'picante', 'Diga as 3 partes de mim que você mais gosta.', null),
  ('desafio', 'picante', 'Morda o lábio e me olhe fixo por 10 segundos sem rir.', null),
  ('desafio', 'picante', 'Escreva e leia em voz alta uma mensagem picante de 3 linhas.', null),
  ('desafio', 'picante', 'Tire uma peça de roupa (acessório também conta).', null),
  ('desafio', 'picante', 'Descreva em detalhes como vai ser o nosso reencontro.', null),
  ('desafio', 'picante', 'Massageie o próprio pescoço narrando como se fossem as minhas mãos.', null),
  ('desafio', 'picante', 'Mande um áudio de 15 segundos sussurrando o meu nome.', 'audio'),
  ('desafio', 'picante', 'Mostre na câmera a roupa íntima que você está usando agora.', null),
  ('desafio', 'picante', 'Faça um desfile de lingerie ou cueca na música que eu escolher.', null),
  ('desafio', 'picante', 'Tire uma selfie no espelho só de roupa íntima e mande.', 'foto'),
  ('desafio', 'picante', 'Beije a própria mão bem devagar olhando para a câmera.', null),
  ('desafio', 'picante', 'Conte em voz baixa o que vai fazer comigo no reencontro.', null),
  ('desafio', 'picante', 'Passe a mão devagar pelo pescoço enquanto me olha.', null),
  ('desafio', 'picante', 'Mande uma foto da parte do seu corpo que você acha mais sexy.', 'foto'),
  ('desafio', 'picante', 'Faça uma pose sensual e segure por 10 segundos.', null),
  ('desafio', 'picante', 'Escreva no chat 3 coisas que você quer fazer comigo.', null),
  ('desafio', 'picante', 'Grave um vídeo de 10 segundos mandando um beijo do jeito mais provocante.', 'video'),
  ('desafio', 'picante', 'Deite na cama e me mostre como estaria me esperando.', null),
  ('desafio', 'picante', 'Tire a camiseta e continue assim até o fim da próxima rodada.', null),
  ('desafio', 'picante', 'Morda uma fruta ou um chocolate do jeito mais provocante possível.', null),
  ('desafio', 'picante', 'Me olhe como se me visse do outro lado de uma festa.', null),
  ('desafio', 'picante', 'Leia uma mensagem que eu te escrever com a sua voz mais sedutora.', null),
  ('desafio', 'picante', 'Mande uma foto de costas usando só a peça que eu escolher.', 'foto'),
  ('desafio', 'picante', 'Faça o seu melhor olhar de "vem cá" por 5 segundos.', null),
  ('desafio', 'picante', 'Me dê uma ordem provocante que eu vou ter que cumprir na próxima rodada.', null),
  ('desafio', 'picante', 'Faça um striptease de uma peça só, bem devagar.', null),
  ('desafio', 'picante', 'Descreva a sua posição favorita sem dizer o nome, até eu adivinhar.', null),
  ('desafio', 'picante', 'Me mostre com as mãos, pela câmera, a posição que você mais quer repetir.', null),
  ('desafio', 'picante', 'Escolha a posição da nossa primeira noite do reencontro e diga por quê.', null),
  ('desafio', 'picante', 'Deite na posição em que gostaria de dormir abraçado(a) comigo e me mostre.', null),
  ('desafio', 'picante', 'Faça um ranking das suas 3 posições favoritas.', null),
  ('desafio', 'picante', 'Procure o nome de uma posição que a gente nunca fez e me conte o que achou.', null),
  ('desafio', 'picante', 'Desenhe com bonecos de palito a posição que você quer tentar.', null),
  ('desafio', 'picante', 'Diga qual posição combina com cada dia da semana.', null),
  ('desafio', 'picante', 'Escolha uma posição para eu "estudar" até o reencontro.', null),
  ('desafio', 'picante', 'Mostre na câmera como você me puxaria para perto.', null)
on conflict do nothing;

-- desafio · pesado (40)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('desafio', 'pesado', 'Tire uma peça de roupa bem devagar, na música que eu escolher.', null),
  ('desafio', 'pesado', 'Conte em detalhes a sua fantasia mais ousada comigo.', null),
  ('desafio', 'pesado', 'Mande uma foto ousada (o limite é seu).', 'foto'),
  ('desafio', 'pesado', 'Eu escolho o que você vai vestir pelo resto da chamada.', null),
  ('desafio', 'pesado', 'Siga as minhas instruções por 2 minutos, com direito a vetar qualquer uma.', null),
  ('desafio', 'pesado', 'Mande um nude, com o enquadramento que você escolher.', 'foto'),
  ('desafio', 'pesado', 'Grave um vídeo sensual de 15 segundos e mande.', 'video'),
  ('desafio', 'pesado', 'Fique sem roupa até o fim da próxima rodada, com a câmera no ângulo que você quiser.', null),
  ('desafio', 'pesado', 'Faça um striptease completo, no seu ritmo, na música que eu escolher.', null),
  ('desafio', 'pesado', 'Mande um áudio contando em detalhes o que quer que eu faça com você.', 'audio'),
  ('desafio', 'pesado', 'Escolha uma foto ousada da sua galeria e me mande.', 'foto'),
  ('desafio', 'pesado', 'Deixe eu dirigir uma sessão de fotos sua por 2 minutos, pela câmera.', null),
  ('desafio', 'pesado', 'Tire uma foto sem a parte de cima e mande.', 'foto'),
  ('desafio', 'pesado', 'Faça a pose mais ousada que tiver coragem e segure 10 segundos.', null),
  ('desafio', 'pesado', 'Grave um áudio de 10 segundos dizendo meu nome com a voz mais quente que conseguir.', 'audio'),
  ('desafio', 'pesado', 'Escreva a mensagem mais ousada que você já escreveu e me mande.', null),
  ('desafio', 'pesado', 'Mostre a peça que você tiraria primeiro para mim, e tire.', null),
  ('desafio', 'pesado', 'Mande uma foto saindo do banho.', 'foto'),
  ('desafio', 'pesado', 'Por 1 minuto, faça só o que eu mandar, com direito a veto.', null),
  ('desafio', 'pesado', 'Descreva sua fantasia mais ousada me olhando nos olhos pela câmera.', null),
  ('desafio', 'pesado', 'Mande um vídeo de 10 segundos tirando uma peça de roupa.', 'video'),
  ('desafio', 'pesado', 'Me mostre com as mãos, pela câmera, onde você gostaria de ser beijado(a).', null),
  ('desafio', 'pesado', 'Descreva o nude que você gostaria de receber de mim.', null),
  ('desafio', 'pesado', 'Crie um cupom ousado para usar comigo no reencontro e me mostre.', null),
  ('desafio', 'pesado', 'Sim ou não rápido: eu faço 5 perguntas ousadas e você responde em até 3 segundos cada.', null),
  ('desafio', 'pesado', 'Monte a sua posição favorita com travesseiros e me mostre na câmera.', null),
  ('desafio', 'pesado', 'Mande um áudio contando a posição que você quer comigo e por quê.', 'audio'),
  ('desafio', 'pesado', 'Deite na cama na posição que você mais quer comigo e fique assim 20 segundos.', null),
  ('desafio', 'pesado', 'Eu escolho uma posição e você me explica como faria.', null),
  ('desafio', 'pesado', 'Monte um cardápio de 5 posições para o reencontro e me mande.', null),
  ('desafio', 'pesado', 'Me mostre pela câmera como você estaria na posição que eu escolher (com ou sem roupa, você decide).', null),
  ('desafio', 'pesado', 'Mande uma foto sugerindo a posição que você quer.', 'foto'),
  ('desafio', 'pesado', 'Escolha a posição e o cômodo da casa para a primeira vez no reencontro.', null),
  ('desafio', 'pesado', 'Descreva a posição que te deixa mais sem fôlego.', null),
  ('desafio', 'pesado', 'Grave um vídeo de 10 segundos na posição que você quer que eu imagine.', 'video'),
  ('desafio', 'pesado', 'Crie um desafio de posições para a gente cumprir no reencontro.', null),
  ('desafio', 'pesado', 'Escolha uma posição nova para cada dia do nosso reencontro.', null),
  ('desafio', 'pesado', 'Diga qual posição a gente vai "treinar" primeiro e por quê.', null),
  ('desafio', 'pesado', 'Em 30 segundos, diga o maior número de posições que conseguir lembrar.', null),
  ('desafio', 'pesado', 'Escolha 3 posições e a gente vota na vencedora.', null)
on conflict do nothing;

-- prenda · leve (10)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('prenda', 'leve', 'Faça 3 elogios sinceros para mim olhando na câmera.', null),
  ('prenda', 'leve', 'Faça 15 polichinelos.', null),
  ('prenda', 'leve', 'Cante um trecho da música que eu escolher.', null),
  ('prenda', 'leve', 'Fique 30 segundos parado(a) como estátua na pose que eu escolher.', null),
  ('prenda', 'leve', 'Mande uma selfie com a cara mais feia que conseguir.', 'foto'),
  ('prenda', 'leve', 'Conte um mico que você pagou esta semana.', null),
  ('prenda', 'leve', 'Faça 10 agachamentos.', null),
  ('prenda', 'leve', 'Me chame pelo apelido mais fofo pelas próximas 3 rodadas.', null),
  ('prenda', 'leve', 'Dance 20 segundos sem música.', null),
  ('prenda', 'leve', 'Imite a minha risada.', null)
on conflict do nothing;

-- prenda · criativo (10)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('prenda', 'criativo', 'Desenhe meu retrato em 30 segundos com a mão não dominante.', null),
  ('prenda', 'criativo', 'Faça 2 versos rimando com o meu nome.', null),
  ('prenda', 'criativo', 'Conte uma história de 30 segundos com a palavra que eu escolher.', null),
  ('prenda', 'criativo', 'Imite o personagem que eu escolher até a próxima rodada.', null),
  ('prenda', 'criativo', 'Crie um slogan para mim.', null),
  ('prenda', 'criativo', 'Faça um comercial de 20 segundos de você mesmo(a).', null),
  ('prenda', 'criativo', 'Faça mímica de uma música até eu acertar.', null),
  ('prenda', 'criativo', 'Invente um apelido novo para mim e explique.', null),
  ('prenda', 'criativo', 'Desenhe como você está se sentindo agora.', null),
  ('prenda', 'criativo', 'Narre o que está acontecendo no seu quarto como um jogo de futebol.', null)
on conflict do nothing;

-- prenda · picante (10)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('prenda', 'picante', 'Mande um beijo provocante para a câmera.', null),
  ('prenda', 'picante', 'Diga 3 coisas que você acha sexy em mim.', null),
  ('prenda', 'picante', 'Tire uma peça de roupa (acessório conta).', null),
  ('prenda', 'picante', 'Mande um áudio de 10 segundos com a sua voz mais sedutora.', 'audio'),
  ('prenda', 'picante', 'Faça uma pose sensual por 10 segundos.', null),
  ('prenda', 'picante', 'Morda o lábio me olhando por 10 segundos.', null),
  ('prenda', 'picante', 'Me conte um pensamento quente que você teve esta semana.', null),
  ('prenda', 'picante', 'Sussurre o que faria se eu estivesse aí.', null),
  ('prenda', 'picante', 'Mande uma foto provocante, no nível que você escolher.', 'foto'),
  ('prenda', 'picante', 'Dance sensual por 15 segundos.', null)
on conflict do nothing;

-- prenda · pesado (10)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('prenda', 'pesado', 'Mande um nude.', 'foto'),
  ('prenda', 'pesado', 'Tire duas peças de roupa.', null),
  ('prenda', 'pesado', 'Fique sem a parte de cima até o fim da próxima rodada.', null),
  ('prenda', 'pesado', 'Mande um vídeo sensual de 10 segundos.', 'video'),
  ('prenda', 'pesado', 'Conte uma fantasia sua em detalhes.', null),
  ('prenda', 'pesado', 'Faça o que eu mandar por 1 minuto, com direito a veto.', null),
  ('prenda', 'pesado', 'Mande um áudio ousado de 15 segundos.', 'audio'),
  ('prenda', 'pesado', 'Me mostre pela câmera a posição que eu escolher.', null),
  ('prenda', 'pesado', 'Faça um striptease de 30 segundos.', null),
  ('prenda', 'pesado', 'Escolha um nude para me mandar depois da chamada.', 'foto')
on conflict do nothing;

-- Confira com a tabela do plano:
-- leve 40/70/10 · criativo 26/50/10 · picante 35/45/10 · pesado 30/40/10 (verdades/desafios/prendas)
select tipo, nivel, count(*) from public.cartas where sala is null group by 1, 2 order by 1, 2;
