-- Longe & Perto v6 — cartas românticas, pergunta do dia e boa noite.
-- Rode DEPOIS do 017_v6.sql. Pode rodar de novo.

-- verdade · romantico (30)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('verdade', 'romantico', 'Qual foi o momento em que você teve certeza de que queria ficar comigo?', null),
  ('verdade', 'romantico', 'O que você mais sente falta de mim no dia a dia?', null),
  ('verdade', 'romantico', 'Qual lembrança nossa te faz sorrir sozinho(a)?', null),
  ('verdade', 'romantico', 'O que você sentiu no nosso primeiro beijo?', null),
  ('verdade', 'romantico', 'Qual foi a coisa mais bonita que eu já te disse?', null),
  ('verdade', 'romantico', 'Como você imagina a nossa casa um dia?', null),
  ('verdade', 'romantico', 'Qual música te faz lembrar do nosso começo?', null),
  ('verdade', 'romantico', 'O que eu faço que te faz se sentir amado(a)?', null),
  ('verdade', 'romantico', 'Qual foi o dia em que você mais sentiu orgulho de nós?', null),
  ('verdade', 'romantico', 'O que você gostaria de me dizer e ainda não disse?', null),
  ('verdade', 'romantico', 'Qual lugar você sonha em conhecer comigo?', null),
  ('verdade', 'romantico', 'O que mudou em você desde que a gente começou a namorar?', null),
  ('verdade', 'romantico', 'Qual abraço meu você nunca esqueceu?', null),
  ('verdade', 'romantico', 'Qual é o seu jeito favorito de receber carinho a distância?', null),
  ('verdade', 'romantico', 'Qual pequeno detalhe meu você acha lindo?', null),
  ('verdade', 'romantico', 'O que você pensa antes de dormir quando sente saudade?', null),
  ('verdade', 'romantico', 'Qual promessa você quer me fazer hoje?', null),
  ('verdade', 'romantico', 'Qual mensagem minha você mais releu?', null),
  ('verdade', 'romantico', 'Qual data nossa é a mais especial para você?', null),
  ('verdade', 'romantico', 'O que você quer que a gente faça no primeiro dia depois que a distância acabar?', null),
  ('verdade', 'romantico', 'Qual foi a vez em que eu te ajudei sem saber?', null),
  ('verdade', 'romantico', 'Que apelido você gostaria de ganhar de mim?', null),
  ('verdade', 'romantico', 'O que te faz ter certeza de que a distância vale a pena?', null),
  ('verdade', 'romantico', 'Qual foto nossa você colocaria num porta-retrato?', null),
  ('verdade', 'romantico', 'Como você descreveria o nosso amor para alguém que não nos conhece?', null),
  ('verdade', 'romantico', 'Qual sonho você quer realizar comigo nos próximos anos?', null),
  ('verdade', 'romantico', 'Qual foi o momento mais engraçado que a gente viveu junto?', null),
  ('verdade', 'romantico', 'O que você mais admira no jeito como eu te trato?', null),
  ('verdade', 'romantico', 'Se pudesse reviver um dia nosso, qual seria?', null),
  ('verdade', 'romantico', 'O que você quer ouvir de mim agora?', null)
on conflict do nothing;

-- desafio · romantico (30)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('desafio', 'romantico', 'Olhe nos meus olhos pela câmera por 20 segundos, sem falar nada.', null),
  ('desafio', 'romantico', 'Diga três coisas que você ama em mim, olhando para a câmera.', null),
  ('desafio', 'romantico', 'Encoste a mão na tela e segure até eu encostar a minha também.', null),
  ('desafio', 'romantico', 'Faça um coração com as mãos e segure até eu fazer também.', null),
  ('desafio', 'romantico', 'Cante um trecho da música que te lembra de mim.', null),
  ('desafio', 'romantico', 'Escreva o meu nome num papel, desenhe um coração e mostre na câmera.', null),
  ('desafio', 'romantico', 'Descreva o abraço que vai me dar no reencontro.', null),
  ('desafio', 'romantico', 'Leia em voz alta a mensagem mais antiga que você achar nossa.', null),
  ('desafio', 'romantico', 'Mostre algo aí que te lembra de mim e conte por quê.', null),
  ('desafio', 'romantico', 'Faça uma declaração de amor de 30 segundos, sem rir.', null),
  ('desafio', 'romantico', 'Deite no travesseiro e me dê boa noite como se eu estivesse do seu lado.', null),
  ('desafio', 'romantico', 'Escreva um bilhete à mão para mim e mostre na câmera.', null),
  ('desafio', 'romantico', 'Conte como foi o seu dia, dizendo em que momento pensou em mim.', null),
  ('desafio', 'romantico', 'Grave um áudio curto dizendo por que você me escolheu.', 'audio'),
  ('desafio', 'romantico', 'Desenhe nós dois no reencontro e mostre na câmera.', null),
  ('desafio', 'romantico', 'Planeje em 1 minuto o nosso próximo encontro perfeito.', null),
  ('desafio', 'romantico', 'Diga "eu te amo" de três jeitos diferentes.', null),
  ('desafio', 'romantico', 'Encoste a testa na câmera como se estivesse encostando na minha.', null),
  ('desafio', 'romantico', 'Conte um sonho seu comigo, com detalhes.', null),
  ('desafio', 'romantico', 'Escolha uma música para a gente dançar junto pela câmera, cada um no seu quarto.', null),
  ('desafio', 'romantico', 'Faça uma promessa para mim e escreva no chat para eu guardar.', null),
  ('desafio', 'romantico', 'Mostre o céu da sua janela e descreva como seria se eu estivesse aí vendo junto.', null),
  ('desafio', 'romantico', 'Diga o que você mais gosta na minha voz.', null),
  ('desafio', 'romantico', 'Faça um brinde ao nosso namoro pela câmera, com o que tiver aí.', null),
  ('desafio', 'romantico', 'Escreva no chat uma frase que você quer que eu lembre para sempre.', null),
  ('desafio', 'romantico', 'Mostre o seu sorriso mais bobo para a câmera, pensando em mim.', null),
  ('desafio', 'romantico', 'Conte como você me descreveria para a sua avó.', null),
  ('desafio', 'romantico', 'Me dê um apelido novo e explique de onde ele veio.', null),
  ('desafio', 'romantico', 'Leia um trecho de livro ou de poema que te lembre de nós.', null),
  ('desafio', 'romantico', 'Mande uma foto de onde você está agora, para eu me sentir aí com você.', 'foto')
on conflict do nothing;

-- prenda · romantico (15)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('prenda', 'romantico', 'Diga "eu te amo" em três idiomas.', null),
  ('prenda', 'romantico', 'Mande um beijo para a câmera.', null),
  ('prenda', 'romantico', 'Faça um elogio sincero olhando nos meus olhos.', null),
  ('prenda', 'romantico', 'Cante "parabéns" para o nosso namoro.', null),
  ('prenda', 'romantico', 'Me chame pelo apelido mais fofo até a próxima rodada.', null),
  ('prenda', 'romantico', 'Faça um coração com as mãos por 10 segundos.', null),
  ('prenda', 'romantico', 'Conte uma lembrança nossa em 20 segundos.', null),
  ('prenda', 'romantico', 'Mande no chat um coração para cada ano que você quer passar comigo.', null),
  ('prenda', 'romantico', 'Diga uma coisa que você quer fazer comigo no reencontro.', null),
  ('prenda', 'romantico', 'Faça uma carinha fofa e segure até eu sorrir.', null),
  ('prenda', 'romantico', 'Escreva o meu nome no ar com o dedo.', null),
  ('prenda', 'romantico', 'Abrace o travesseiro fingindo que sou eu.', null),
  ('prenda', 'romantico', 'Diga por que você está com saudade de mim hoje.', null),
  ('prenda', 'romantico', 'Faça uma promessa fofa para esta semana.', null),
  ('prenda', 'romantico', 'Mande um áudio de 5 segundos dizendo o meu nome com carinho.', 'audio')
on conflict do nothing;

-- pergunta_dia · leve (40)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('pergunta_dia', 'leve', 'O que te fez sorrir hoje?', null),
  ('pergunta_dia', 'leve', 'Qual foi a parte mais difícil do seu dia?', null),
  ('pergunta_dia', 'leve', 'O que você comeu de melhor hoje?', null),
  ('pergunta_dia', 'leve', 'Em que momento de hoje você pensou em mim?', null),
  ('pergunta_dia', 'leve', 'Qual música não sai da sua cabeça hoje?', null),
  ('pergunta_dia', 'leve', 'Se eu estivesse aí agora, o que a gente estaria fazendo?', null),
  ('pergunta_dia', 'leve', 'O que você quer fazer amanhã?', null),
  ('pergunta_dia', 'leve', 'De 0 a 10, quanta saudade você está sentindo hoje?', null),
  ('pergunta_dia', 'leve', 'O que você aprendeu hoje?', null),
  ('pergunta_dia', 'leve', 'Qual foi a coisa mais engraçada que aconteceu hoje?', null),
  ('pergunta_dia', 'leve', 'Com quem você conversou hoje que gostaria que eu conhecesse?', null),
  ('pergunta_dia', 'leve', 'O que você está com vontade de comer agora?', null),
  ('pergunta_dia', 'leve', 'O que te deixou orgulhoso(a) de você hoje?', null),
  ('pergunta_dia', 'leve', 'Qual foi o melhor momento da sua semana até agora?', null),
  ('pergunta_dia', 'leve', 'O que está te preocupando esses dias?', null),
  ('pergunta_dia', 'leve', 'Qual plano nosso você mais quer realizar?', null),
  ('pergunta_dia', 'leve', 'O que você faria se tivesse o dia de amanhã livre?', null),
  ('pergunta_dia', 'leve', 'Qual cheiro te lembra de mim?', null),
  ('pergunta_dia', 'leve', 'Que lugar da sua cidade você quer me mostrar?', null),
  ('pergunta_dia', 'leve', 'O que você quer me contar e ainda não contou?', null),
  ('pergunta_dia', 'leve', 'Com o que você sonhou esta noite?', null),
  ('pergunta_dia', 'leve', 'Qual série ou vídeo você viu hoje?', null),
  ('pergunta_dia', 'leve', 'Como está o tempo aí agora?', null),
  ('pergunta_dia', 'leve', 'O que você mais precisa ouvir hoje?', null),
  ('pergunta_dia', 'leve', 'Qual foi a última coisa que te fez chorar de rir?', null),
  ('pergunta_dia', 'leve', 'Qual hábito você quer mudar este mês?', null),
  ('pergunta_dia', 'leve', 'Pelo que você agradece hoje?', null),
  ('pergunta_dia', 'leve', 'Qual lembrança nossa apareceu na sua cabeça hoje?', null),
  ('pergunta_dia', 'leve', 'Se hoje fosse um emoji, qual seria?', null),
  ('pergunta_dia', 'leve', 'Qual é o seu desejo para esta semana?', null),
  ('pergunta_dia', 'leve', 'Qual detalhe do seu quarto eu ainda não conheço?', null),
  ('pergunta_dia', 'leve', 'O que você mais gostou na nossa última chamada?', null),
  ('pergunta_dia', 'leve', 'Que música você me dedicaria hoje?', null),
  ('pergunta_dia', 'leve', 'O que você quer que eu faça por você amanhã?', null),
  ('pergunta_dia', 'leve', 'Qual foi a decisão mais difícil do seu dia?', null),
  ('pergunta_dia', 'leve', 'O que você está lendo, vendo ou ouvindo esses dias?', null),
  ('pergunta_dia', 'leve', 'O que você quer que aconteça no nosso reencontro?', null),
  ('pergunta_dia', 'leve', 'Que presente você me daria hoje, se pudesse?', null),
  ('pergunta_dia', 'leve', 'Qual frase resume o seu dia?', null),
  ('pergunta_dia', 'leve', 'O que te deu paz hoje?', null)
on conflict do nothing;

-- boa_noite · romantico (20)
insert into public.cartas (tipo, nivel, texto, midia) values
  ('boa_noite', 'romantico', 'Durma bem. Amanhã é um dia a menos até a gente se ver.', null),
  ('boa_noite', 'romantico', 'Boa noite, meu amor. Hoje fiquei um pouco mais perto de você.', null),
  ('boa_noite', 'romantico', 'Que o sono seja leve e o sonho seja comigo.', null),
  ('boa_noite', 'romantico', 'A distância é só no mapa. Boa noite.', null),
  ('boa_noite', 'romantico', 'Fecha os olhos: estou te dando um abraço daqui.', null),
  ('boa_noite', 'romantico', 'Obrigado(a) por hoje. Boa noite, amor.', null),
  ('boa_noite', 'romantico', 'Mais um dia juntos, mesmo longe. Durma bem.', null),
  ('boa_noite', 'romantico', 'Boa noite para a pessoa que eu mais queria do meu lado agora.', null),
  ('boa_noite', 'romantico', 'Até amanhã. Guarda um beijo meu no travesseiro.', null),
  ('boa_noite', 'romantico', 'Hoje foi bom porque teve você. Boa noite.', null),
  ('boa_noite', 'romantico', 'Descansa. Eu continuo aqui.', null),
  ('boa_noite', 'romantico', 'O reencontro está mais perto do que ontem. Boa noite.', null),
  ('boa_noite', 'romantico', 'Sonha com a gente. Eu vou sonhar também.', null),
  ('boa_noite', 'romantico', 'Boa noite, meu lugar favorito.', null),
  ('boa_noite', 'romantico', 'Que amanhã a saudade seja menor e o amor, maior ainda.', null),
  ('boa_noite', 'romantico', 'Dorme bem, que amanhã tem mais de nós.', null),
  ('boa_noite', 'romantico', 'Um beijo na testa e boa noite.', null),
  ('boa_noite', 'romantico', 'Longe dos olhos, perto de todo o resto. Boa noite.', null),
  ('boa_noite', 'romantico', 'Se você acordar de madrugada, lembra: eu te amo.', null),
  ('boa_noite', 'romantico', 'Boa noite. Obrigado(a) por escolher a gente todo dia.', null)
on conflict do nothing;

select tipo, nivel, count(*) from public.cartas where sala is null and (nivel = 'romantico' or tipo = 'pergunta_dia') group by 1, 2 order by 1, 2;
