-- Longe & Perto v8 — cartas com continuação e roteiros de sessão.
-- Rode DEPOIS do 022_v8.sql. Pode rodar de novo.

-- sequencia (20)
insert into public.cartas (tipo, nivel, texto, etapas) values
  ('sequencia', 'romantico', 'Lembrança secreta', '[{"quem": "vez", "texto": "Escolha uma lembrança nossa, sem contar qual."}, {"quem": "outro", "texto": "Tente adivinhar qual é a lembrança, com até 3 palpites."}, {"quem": "dois", "texto": "Cada um conta um detalhe dessa lembrança que nunca disse."}]'::jsonb),
  ('sequencia', 'romantico', 'Duas palavras', '[{"quem": "vez", "texto": "Diga em voz alta uma palavra que resume o nosso namoro."}, {"quem": "outro", "texto": "Agora diga a sua palavra."}, {"quem": "dois", "texto": "Expliquem por que escolheram essas palavras."}]'::jsonb),
  ('sequencia', 'romantico', 'Primeiro encontro', '[{"quem": "vez", "texto": "Descreva o nosso primeiro encontro em uma frase."}, {"quem": "outro", "texto": "Complete a frase com o que ficou de fora."}, {"quem": "dois", "texto": "Combinem uma coisa daquele dia para repetir no reencontro."}]'::jsonb),
  ('sequencia', 'romantico', 'Pergunta guardada', '[{"quem": "vez", "texto": "Faça uma pergunta que você nunca teve coragem de me fazer."}, {"quem": "outro", "texto": "Responda com sinceridade."}, {"quem": "vez", "texto": "Conte por que você queria saber isso."}]'::jsonb),
  ('sequencia', 'leve', 'Objeto misterioso', '[{"quem": "vez", "texto": "Pense num objeto da sua casa, sem dizer qual."}, {"quem": "outro", "texto": "Faça até 5 perguntas de sim ou não para adivinhar."}, {"quem": "vez", "texto": "Mostre o objeto na câmera e conte a história dele."}]'::jsonb),
  ('sequencia', 'leve', 'Quem sou eu', '[{"quem": "vez", "texto": "Imite uma pessoa famosa, sem dizer quem é."}, {"quem": "outro", "texto": "Adivinhe. Se errar, imite outra pessoa famosa para eu adivinhar."}]'::jsonb),
  ('sequencia', 'leve', 'Duas verdades e uma mentira', '[{"quem": "vez", "texto": "Diga três coisas sobre você: duas verdades e uma mentira."}, {"quem": "outro", "texto": "Adivinhe qual é a mentira."}, {"quem": "vez", "texto": "Conte a história de uma das verdades."}]'::jsonb),
  ('sequencia', 'leve', 'Nossa casa', '[{"quem": "vez", "texto": "Complete em voz alta: \"Se a gente morasse junto…\""}, {"quem": "outro", "texto": "Continue a frase."}, {"quem": "dois", "texto": "Decidam juntos a regra mais importante da casa."}]'::jsonb),
  ('sequencia', 'criativo', 'Desenho secreto', '[{"quem": "vez", "texto": "Desenhe algo em 30 segundos, sem mostrar."}, {"quem": "outro", "texto": "Adivinhe o desenho com 3 dicas que eu der."}, {"quem": "vez", "texto": "Mostre o desenho na câmera."}]'::jsonb),
  ('sequencia', 'criativo', 'O filme de nós dois', '[{"quem": "vez", "texto": "Invente o título de um filme sobre nós."}, {"quem": "outro", "texto": "Invente a sinopse."}, {"quem": "dois", "texto": "Escolham juntos quem seriam os atores."}]'::jsonb),
  ('sequencia', 'criativo', 'Música a quatro mãos', '[{"quem": "vez", "texto": "Crie o primeiro verso de uma música sobre nós."}, {"quem": "outro", "texto": "Crie o segundo verso."}, {"quem": "dois", "texto": "Cantem os dois versos juntos."}]'::jsonb),
  ('sequencia', 'criativo', 'Estátua espelhada', '[{"quem": "vez", "texto": "Faça uma pose de estátua."}, {"quem": "outro", "texto": "Imite a pose igualzinho."}, {"quem": "dois", "texto": "Façam uma pose juntos, como se estivessem na mesma foto."}]'::jsonb),
  ('sequencia', 'picante', 'Parte secreta', '[{"quem": "vez", "texto": "Escolha uma parte do meu corpo, sem dizer qual."}, {"quem": "outro", "texto": "Adivinhe qual é, com até 3 palpites."}, {"quem": "vez", "texto": "Diga o que faria com ela se eu estivesse aí."}]'::jsonb),
  ('sequencia', 'picante', 'Tira ou fica', '[{"quem": "vez", "texto": "Mostre por 3 segundos uma peça de roupa que você está usando."}, {"quem": "outro", "texto": "Escolha: tira ou fica."}, {"quem": "vez", "texto": "Cumpra a escolha."}]'::jsonb),
  ('sequencia', 'picante', 'Palavra por palavra', '[{"quem": "vez", "texto": "Sussurre uma palavra provocante."}, {"quem": "outro", "texto": "Responda com outra palavra provocante."}, {"quem": "dois", "texto": "Continuem, um de cada vez, até alguém rir."}]'::jsonb),
  ('sequencia', 'picante', 'Beijo endereçado', '[{"quem": "vez", "texto": "Descreva um beijo que você quer me dar."}, {"quem": "outro", "texto": "Diga onde quer receber esse beijo."}, {"quem": "vez", "texto": "Mande esse beijo para a câmera, olhando para mim."}]'::jsonb),
  ('sequencia', 'pesado', 'Fantasia a dois', '[{"quem": "vez", "texto": "Conte o começo de uma fantasia comigo."}, {"quem": "outro", "texto": "Continue a fantasia."}, {"quem": "vez", "texto": "Conte como ela termina."}]'::jsonb),
  ('sequencia', 'pesado', 'Peça por peça', '[{"quem": "vez", "texto": "Tire uma peça de roupa."}, {"quem": "outro", "texto": "Tire uma peça também."}, {"quem": "dois", "texto": "Fiquem assim até o fim da próxima rodada."}]'::jsonb),
  ('sequencia', 'pesado', 'Posição secreta', '[{"quem": "vez", "texto": "Escolha uma posição para o reencontro, sem dizer qual."}, {"quem": "outro", "texto": "Adivinhe qual é, com até 3 palpites."}, {"quem": "vez", "texto": "Mostre pela câmera como seria."}]'::jsonb),
  ('sequencia', 'pesado', 'Mostra de novo', '[{"quem": "vez", "texto": "Mostre por 3 segundos a parte do seu corpo de que você mais gosta."}, {"quem": "outro", "texto": "Diga o que achou, com detalhes."}, {"quem": "vez", "texto": "Mostre de novo, agora por 10 segundos."}]'::jsonb)
on conflict do nothing;

-- roteiros (6)
insert into public.roteiros (nome, emoji, descricao, nivel_max, etapas, ordem) values
  ('Só risadas', '😂', 'Para rir muito: aquecimento, improvisos, um duelo e uma missão em dupla no final.', 'criativo', '[{"nome": "Aquecimento", "rodadas": 2, "niveis": ["leve"], "tipos": ["verdade"]}, {"nome": "Improvisos", "rodadas": 3, "niveis": ["criativo"], "tipos": ["desafio"]}, {"nome": "Duelo", "rodadas": 1, "niveis": ["leve", "criativo"], "tipos": ["duelo"]}, {"nome": "Juntos no final", "rodadas": 1, "niveis": ["leve", "criativo"], "tipos": ["missao_dupla"]}]'::jsonb, 1),
  ('Noite romântica', '💗', 'Calma e carinhosa: perguntas, carinhos pela câmera e uma sequência a dois.', 'romantico', '[{"nome": "Conversa", "rodadas": 3, "niveis": ["romantico"], "tipos": ["verdade"]}, {"nome": "Carinhos", "rodadas": 2, "niveis": ["romantico"], "tipos": ["desafio"]}, {"nome": "A dois", "rodadas": 1, "niveis": ["romantico"], "tipos": ["sequencia"]}, {"nome": "Boa noite", "rodadas": 0, "niveis": ["romantico"], "tipos": ["encerrar"]}]'::jsonb, 2),
  ('Esquenta', '🔥', 'Começa leve e vai esquentando aos poucos, até um duelo picante.', 'picante', '[{"nome": "Leve", "rodadas": 2, "niveis": ["leve"], "tipos": ["verdade", "desafio"]}, {"nome": "Criativo", "rodadas": 2, "niveis": ["criativo"], "tipos": ["desafio"]}, {"nome": "Picante", "rodadas": 3, "niveis": ["picante"], "tipos": ["verdade", "desafio"]}, {"nome": "Duelo final", "rodadas": 1, "niveis": ["picante"], "tipos": ["duelo"]}]'::jsonb, 3),
  ('Noite quente', '🌶️', 'Direto ao ponto: picante, depois pesado, com uma sequência ousada no final.', 'pesado', '[{"nome": "Provocação", "rodadas": 2, "niveis": ["picante"], "tipos": ["verdade", "desafio"]}, {"nome": "Sem filtro", "rodadas": 3, "niveis": ["pesado"], "tipos": ["verdade", "desafio"]}, {"nome": "Até o fim", "rodadas": 1, "niveis": ["pesado"], "tipos": ["sequencia"]}]'::jsonb, 4),
  ('Criatividade total', '🎨', 'Desenhos, histórias e imitações do começo ao fim.', 'criativo', '[{"nome": "Aquecendo a imaginação", "rodadas": 2, "niveis": ["criativo"], "tipos": ["verdade"]}, {"nome": "Mão na massa", "rodadas": 3, "niveis": ["criativo"], "tipos": ["desafio"]}, {"nome": "Obra a dois", "rodadas": 1, "niveis": ["criativo"], "tipos": ["sequencia"]}, {"nome": "Missão final", "rodadas": 1, "niveis": ["criativo"], "tipos": ["missao_dupla"]}]'::jsonb, 5),
  ('Antes do reencontro', '✈️', 'Para a última semana de distância: saudade, planos e um pouco de provocação.', 'picante', '[{"nome": "Saudade", "rodadas": 2, "niveis": ["romantico"], "tipos": ["verdade"]}, {"nome": "Planos", "rodadas": 2, "niveis": ["picante"], "tipos": ["verdade", "desafio"]}, {"nome": "Contagem regressiva", "rodadas": 1, "niveis": ["picante"], "tipos": ["sequencia"]}, {"nome": "Para o cofre", "rodadas": 0, "niveis": ["picante"], "tipos": ["cofre"]}]'::jsonb, 6)
on conflict (nome) do nothing;

select 'sequências' as o_que, count(*) from public.cartas where tipo = 'sequencia' and sala is null
union all select 'roteiros', count(*) from public.roteiros;
