-- Longe & Perto — equilíbrio Perto × Longe.
-- Deixa os desafios e prendas presenciais com a mesma quantidade dos de distância, nível a nível.
-- Rode DEPOIS do 025_presencial.sql. Pode rodar de novo.

-- desafio presencial · romantico (+60)
insert into public.cartas (tipo, nivel, texto, modo) values
  ('desafio', 'romantico', 'Leia em voz alta, olhando para mim, a mensagem mais bonita que eu te mandei a distância.', 'presencial'),
  ('desafio', 'romantico', 'Me dê um abraço apertado e conte até 20 sem soltar.', 'presencial'),
  ('desafio', 'romantico', 'Faça carinho nas minhas mãos e diga o que você quer fazer com elas pelo resto da vida.', 'presencial'),
  ('desafio', 'romantico', 'Escolha uma música e cantem juntos olhando um para o outro.', 'presencial'),
  ('desafio', 'romantico', 'Me dê um beijo demorado na bochecha e diga um apelido novo.', 'presencial'),
  ('desafio', 'romantico', 'Deite com a cabeça no meu peito e me diga o que está escutando.', 'presencial'),
  ('desafio', 'romantico', 'Encoste a testa na minha e fiquem assim por 30 segundos.', 'presencial'),
  ('desafio', 'romantico', 'Me conte, abraçado(a), o que você sentiu quando me viu chegando.', 'presencial'),
  ('desafio', 'romantico', 'Faça um coração com as nossas mãos juntas.', 'presencial'),
  ('desafio', 'romantico', 'Me dê um beijo em cada dedo da mão.', 'presencial'),
  ('desafio', 'romantico', 'Me leve pela mão até o lugar mais bonito da casa.', 'presencial'),
  ('desafio', 'romantico', 'Escreva um bilhete agora e coloque no meu bolso para eu ler depois.', 'presencial'),
  ('desafio', 'romantico', 'Faça uma trança ou carinho no meu cabelo enquanto conta um sonho seu.', 'presencial'),
  ('desafio', 'romantico', 'Me olhe nos olhos e diga "obrigado(a) por esperar".', 'presencial'),
  ('desafio', 'romantico', 'Deitem lado a lado e contem um para o outro o melhor momento do dia.', 'presencial'),
  ('desafio', 'romantico', 'Me dê um beijo surpresa quando eu menos esperar nesta rodada.', 'presencial'),
  ('desafio', 'romantico', 'Faça um brinde comigo a nós dois.', 'presencial'),
  ('desafio', 'romantico', 'Sente atrás de mim e me abrace com as pernas também.', 'presencial'),
  ('desafio', 'romantico', 'Me diga 3 coisas que você reparou em mim hoje que não via pela câmera.', 'presencial'),
  ('desafio', 'romantico', 'Desenhe com o dedo um coração no meu rosto.', 'presencial'),
  ('desafio', 'romantico', 'Escolha uma foto nossa no celular e recriem a pose agora.', 'presencial'),
  ('desafio', 'romantico', 'Faça massagem nas minhas mãos com creme.', 'presencial'),
  ('desafio', 'romantico', 'Me conte em voz baixa como imagina nossa vida morando junto.', 'presencial'),
  ('desafio', 'romantico', 'Me dê um beijo na nuca e diga "saudade de você aqui".', 'presencial'),
  ('desafio', 'romantico', 'Escolham juntos o próximo lugar para viajar e dêem as mãos como promessa.', 'presencial'),
  ('desafio', 'romantico', 'Me sirva o primeiro pedaço de algo que estiver comendo.', 'presencial'),
  ('desafio', 'romantico', 'Fiquem 1 minuto em silêncio só se olhando, segurando as mãos.', 'presencial'),
  ('desafio', 'romantico', 'Diga meu nome bem baixinho no meu ouvido, três vezes.', 'presencial'),
  ('desafio', 'romantico', 'Faça uma dedicatória de música e dancem juntos.', 'presencial'),
  ('desafio', 'romantico', 'Me ajude a vestir um casaco ou blusa, com todo o cuidado.', 'presencial'),
  ('desafio', 'romantico', 'Me dê um beijo para cada ano que você quer passar comigo.', 'presencial'),
  ('desafio', 'romantico', 'Encostem os narizes e digam um "eu te amo" ao mesmo tempo.', 'presencial'),
  ('desafio', 'romantico', 'Me leve um café, chá ou suco feito por você.', 'presencial'),
  ('desafio', 'romantico', 'Me abrace e diga o que mais te faz falta quando estamos longe.', 'presencial'),
  ('desafio', 'romantico', 'Me conte uma coisa que você guardou para falar só pessoalmente.', 'presencial'),
  ('desafio', 'romantico', 'Segure minha mão e me dê um passeio de 2 minutos pela casa contando histórias.', 'presencial'),
  ('desafio', 'romantico', 'Faça um carinho nas minhas costas desenhando estrelas.', 'presencial'),
  ('desafio', 'romantico', 'Diga a primeira coisa que pensou quando me abraçou hoje.', 'presencial'),
  ('desafio', 'romantico', 'Deite comigo e cubram-se juntos com um lençol por 2 minutos.', 'presencial'),
  ('desafio', 'romantico', 'Me dê um beijo nas pálpebras, bem devagar.', 'presencial'),
  ('desafio', 'romantico', 'Escrevam juntos uma lista de 3 coisas para fazer antes de se despedirem.', 'presencial'),
  ('desafio', 'romantico', 'Me abrace por 1 minuto inteiro sem dizer nada.', 'presencial'),
  ('desafio', 'romantico', 'Me dê um beijo de cinema, com direito a inclinar para trás.', 'presencial'),
  ('desafio', 'romantico', 'Faça uma promessa olhando nos meus olhos e selem com o dedinho.', 'presencial'),
  ('desafio', 'romantico', 'Me penteie como se fosse um cabeleireiro carinhoso.', 'presencial'),
  ('desafio', 'romantico', 'Diga uma frase bonita e me dê um beijo depois de cada palavra.', 'presencial'),
  ('desafio', 'romantico', 'Me guie de olhos fechados até um lugar da casa e me surpreenda com um beijo.', 'presencial'),
  ('desafio', 'romantico', 'Pegue minhas mãos e coloque no seu coração por 10 segundos.', 'presencial'),
  ('desafio', 'romantico', 'Escolha uma lembrança nossa e me conte de novo, abraçado(a).', 'presencial'),
  ('desafio', 'romantico', 'Faça um cafuné enquanto eu deito no seu colo, por 3 minutos.', 'presencial'),
  ('desafio', 'romantico', 'Me dê um selinho a cada vez que eu sorrir, por 1 minuto.', 'presencial'),
  ('desafio', 'romantico', 'Me diga o que você vai sentir quando eu for embora e me abrace.', 'presencial'),
  ('desafio', 'romantico', 'Me faça um carinho no rosto com o seu.', 'presencial'),
  ('desafio', 'romantico', 'Peça para eu fechar os olhos e me dê um presente feito na hora.', 'presencial'),
  ('desafio', 'romantico', 'Me conte o que sonhou fazer comigo nos dias juntos.', 'presencial'),
  ('desafio', 'romantico', 'Sente no chão comigo e montem juntos uma playlist do reencontro.', 'presencial'),
  ('desafio', 'romantico', 'Me dê um beijo em cada lugar do rosto que você mais gosta.', 'presencial'),
  ('desafio', 'romantico', 'Abrace minhas costas e balancem devagar por 30 segundos.', 'presencial'),
  ('desafio', 'romantico', 'Escrevam o nome do casal no vidro embaçado ou num papel juntos.', 'presencial'),
  ('desafio', 'romantico', 'Me diga, segurando meu rosto, "valeu a pena esperar".', 'presencial')
on conflict do nothing;

-- desafio presencial · leve (+58)
insert into public.cartas (tipo, nivel, texto, modo) values
  ('desafio', 'leve', 'Faça um aviãozinho com a comida e me dê na boca.', 'presencial'),
  ('desafio', 'leve', 'Jogue par ou ímpar comigo: quem perder faz uma imitação.', 'presencial'),
  ('desafio', 'leve', 'Me faça um penteado maluco e tire uma foto.', 'presencial'),
  ('desafio', 'leve', 'Briguem de dedinho, melhor de 5.', 'presencial'),
  ('desafio', 'leve', 'Tente me levantar no colo.', 'presencial'),
  ('desafio', 'leve', 'Me deixe fazer cócegas no seu pé por 5 segundos.', 'presencial'),
  ('desafio', 'leve', 'Faça uma careta para cada careta que eu fizer, por 30 segundos.', 'presencial'),
  ('desafio', 'leve', 'Imite um animal e eu tenho 3 chances de acertar.', 'presencial'),
  ('desafio', 'leve', 'Me ensine uma coreografia de 15 segundos.', 'presencial'),
  ('desafio', 'leve', 'Coloquem uma música e dancem trocando de par imaginário.', 'presencial'),
  ('desafio', 'leve', 'Tente me fazer rir sem tocar em mim.', 'presencial'),
  ('desafio', 'leve', 'Joguem "vaca amarela": quem falar primeiro paga prenda.', 'presencial'),
  ('desafio', 'leve', 'Me dê um abraço de lado andando pela casa.', 'presencial'),
  ('desafio', 'leve', 'Equilibrem um objeto entre as testas e andem até o outro lado do cômodo.', 'presencial'),
  ('desafio', 'leve', 'Faça uma bolinha de papel e acerte no meu bolso ou no meu colo.', 'presencial'),
  ('desafio', 'leve', 'Imite como eu fico quando estou com fome.', 'presencial'),
  ('desafio', 'leve', 'Me sirva um lanche como garçom engraçado.', 'presencial'),
  ('desafio', 'leve', 'Me empreste uma peça de roupa sua e eu desfilo com ela.', 'presencial'),
  ('desafio', 'leve', 'Tirem uma selfie com as caras mais feias que conseguirem.', 'presencial'),
  ('desafio', 'leve', 'Faça um sotaque diferente nas próximas 3 frases para mim.', 'presencial'),
  ('desafio', 'leve', 'Jogue pedra, papel e tesoura comigo, melhor de 3.', 'presencial'),
  ('desafio', 'leve', 'Contem juntos até 20 alternando, sem errar.', 'presencial'),
  ('desafio', 'leve', 'Me imite contando uma história engraçada nossa.', 'presencial'),
  ('desafio', 'leve', 'Faça um desfile pela sala como se fosse famoso(a).', 'presencial'),
  ('desafio', 'leve', 'Me ofereça o último pedaço de algo gostoso.', 'presencial'),
  ('desafio', 'leve', 'Me abrace e me levante do chão (ou tente).', 'presencial'),
  ('desafio', 'leve', 'Desenhem um no braço do outro com caneta.', 'presencial'),
  ('desafio', 'leve', 'Me imite dormindo.', 'presencial'),
  ('desafio', 'leve', 'Escondam um objeto e o outro tem 1 minuto para achar.', 'presencial'),
  ('desafio', 'leve', 'Faça uma pose de super-herói comigo para uma foto.', 'presencial'),
  ('desafio', 'leve', 'Toquem uma música batendo na mesa juntos.', 'presencial'),
  ('desafio', 'leve', 'Me conte uma piada de tiozão e tente não rir.', 'presencial'),
  ('desafio', 'leve', 'Me deixe escolher uma música e dance sozinho(a) para mim.', 'presencial'),
  ('desafio', 'leve', 'Me faça uma massagem de 30 segundos nos ombros.', 'presencial'),
  ('desafio', 'leve', 'Comam alguma coisa juntos sem usar as mãos.', 'presencial'),
  ('desafio', 'leve', 'Imite um repórter me entrevistando sobre o reencontro.', 'presencial'),
  ('desafio', 'leve', 'Faça uma estrelinha, cambalhota ou o que conseguir.', 'presencial'),
  ('desafio', 'leve', 'Façam a mesma pose ao mesmo tempo sem combinar, contando até 3.', 'presencial'),
  ('desafio', 'leve', 'Me ensine uma brincadeira da sua infância e joguem uma vez.', 'presencial'),
  ('desafio', 'leve', 'Fale o alfabeto com um beijo entre cada letra.', 'presencial'),
  ('desafio', 'leve', 'Façam guerra de almofada por 20 segundos.', 'presencial'),
  ('desafio', 'leve', 'Imite meu jeito de rir até eu rir de verdade.', 'presencial'),
  ('desafio', 'leve', 'Coloque uma meia na mão e faça um fantoche falar comigo.', 'presencial'),
  ('desafio', 'leve', 'Façam a dança mais boba possível juntos.', 'presencial'),
  ('desafio', 'leve', 'Me dê um apelido engraçado e me chame assim até a próxima rodada.', 'presencial'),
  ('desafio', 'leve', 'Joguem "o mestre mandou" por 1 minuto.', 'presencial'),
  ('desafio', 'leve', 'Me desafie numa queda de braço.', 'presencial'),
  ('desafio', 'leve', 'Me ofereça uma bebida como se fosse num restaurante chique.', 'presencial'),
  ('desafio', 'leve', 'Tirem uma selfie de cabeça para baixo.', 'presencial'),
  ('desafio', 'leve', 'Faça bolinhas de sabão ou bolhas com o que tiver e estoure comigo.', 'presencial'),
  ('desafio', 'leve', 'Conte até 10 em outra língua segurando minha mão.', 'presencial'),
  ('desafio', 'leve', 'Me imite atendendo uma ligação da sua mãe.', 'presencial'),
  ('desafio', 'leve', 'Escrevam uma palavra nas costas do outro e adivinhem.', 'presencial'),
  ('desafio', 'leve', 'Fiquem 20 segundos de mãos dadas pulando num pé só.', 'presencial'),
  ('desafio', 'leve', 'Me faça um sanduíche com um desenho de carinha.', 'presencial'),
  ('desafio', 'leve', 'Desafio do silêncio: quem falar primeiro em 1 minuto paga prenda.', 'presencial'),
  ('desafio', 'leve', 'Me dê um abraço de urso e balance de um lado para o outro.', 'presencial'),
  ('desafio', 'leve', 'Inventem um apelido para o celular e chamem ele assim o dia todo.', 'presencial')
on conflict do nothing;

-- desafio presencial · criativo (+56)
insert into public.cartas (tipo, nivel, texto, modo) values
  ('desafio', 'criativo', 'Façam uma tirinha de 3 quadros sobre o reencontro, cada um desenha um quadro.', 'presencial'),
  ('desafio', 'criativo', 'Inventem juntos o nome e o logo de um restaurante só de vocês.', 'presencial'),
  ('desafio', 'criativo', 'Encene comigo uma cena de novela, com direito a drama.', 'presencial'),
  ('desafio', 'criativo', 'Escreva uma música de 4 versos e cante para mim.', 'presencial'),
  ('desafio', 'criativo', 'Façam uma escultura de massinha, papel ou comida que represente o casal.', 'presencial'),
  ('desafio', 'criativo', 'Monte uma pose de estátua comigo para uma foto artística.', 'presencial'),
  ('desafio', 'criativo', 'Inventem um idioma de 5 palavras e conversem 1 minuto nele.', 'presencial'),
  ('desafio', 'criativo', 'Façam um curta de 30 segundos no celular com um roteiro inventado agora.', 'presencial'),
  ('desafio', 'criativo', 'Me desenhe de olhos fechados em 30 segundos.', 'presencial'),
  ('desafio', 'criativo', 'Montem juntos uma cabana e contem uma história de terror engraçada dentro dela.', 'presencial'),
  ('desafio', 'criativo', 'Criem um brinde oficial do casal, com frase e gesto.', 'presencial'),
  ('desafio', 'criativo', 'Façam uma propaganda de 20 segundos vendendo o abraço do outro.', 'presencial'),
  ('desafio', 'criativo', 'Inventem uma dança para a nossa música e apresentem.', 'presencial'),
  ('desafio', 'criativo', 'Recriem a capa de um álbum famoso com o que tiver em casa.', 'presencial'),
  ('desafio', 'criativo', 'Me ensine a desenhar alguma coisa que você sabe.', 'presencial'),
  ('desafio', 'criativo', 'Façam um quadro juntos, um traço cada, sem combinar o tema.', 'presencial'),
  ('desafio', 'criativo', 'Inventem uma brincadeira de tabuleiro com papel e joguem uma rodada.', 'presencial'),
  ('desafio', 'criativo', 'Escrevam juntos uma carta para vocês mesmos daqui a um ano.', 'presencial'),
  ('desafio', 'criativo', 'Criem um jornal de uma página sobre o reencontro.', 'presencial'),
  ('desafio', 'criativo', 'Façam uma sessão de fotos com tema que eu escolher.', 'presencial'),
  ('desafio', 'criativo', 'Imitem juntos um casal de filme famoso.', 'presencial'),
  ('desafio', 'criativo', 'Montem um prato bonito como chef e sirvam um ao outro.', 'presencial'),
  ('desafio', 'criativo', 'Inventem um superpoder do casal e encenem como usariam.', 'presencial'),
  ('desafio', 'criativo', 'Façam teatro de sombras na parede com uma lanterna.', 'presencial'),
  ('desafio', 'criativo', 'Criem uma palavra-código para "quero um beijo agora".', 'presencial'),
  ('desafio', 'criativo', 'Me faça um retrato com objetos da mesa.', 'presencial'),
  ('desafio', 'criativo', 'Inventem a história de como seria o casamento de vocês, cada um uma frase.', 'presencial'),
  ('desafio', 'criativo', 'Façam uma coreografia com as mãos e gravem para guardar.', 'presencial'),
  ('desafio', 'criativo', 'Recriem juntos uma foto antiga de um de vocês.', 'presencial'),
  ('desafio', 'criativo', 'Decorem um cantinho da casa como se fosse um encontro especial.', 'presencial'),
  ('desafio', 'criativo', 'Escrevam 5 "vales" (vale massagem, vale beijo...) e troquem entre vocês.', 'presencial'),
  ('desafio', 'criativo', 'Inventem um personagem cada e conversem como eles por 1 minuto.', 'presencial'),
  ('desafio', 'criativo', 'Façam uma música só com sons do corpo.', 'presencial'),
  ('desafio', 'criativo', 'Criem um mapa do tesouro com uma surpresa no fim.', 'presencial'),
  ('desafio', 'criativo', 'Dublem juntos uma cena de desenho animado.', 'presencial'),
  ('desafio', 'criativo', 'Inventem um nome para cada cômodo da casa e usem até o fim do dia.', 'presencial'),
  ('desafio', 'criativo', 'Pintem ou desenhem um no papel o rosto do outro e troquem.', 'presencial'),
  ('desafio', 'criativo', 'Encenem o pedido de namoro de um jeito totalmente diferente.', 'presencial'),
  ('desafio', 'criativo', 'Façam uma escultura com o corpo dos dois juntos e segurem 20 segundos.', 'presencial'),
  ('desafio', 'criativo', 'Montem uma playlist com uma música que represente cada mês de namoro.', 'presencial'),
  ('desafio', 'criativo', 'Criem um aperto de mão de 5 passos e façam sem errar.', 'presencial'),
  ('desafio', 'criativo', 'Inventem uma tradição para todo primeiro dia de reencontro.', 'presencial'),
  ('desafio', 'criativo', 'Escrevam um haicai cada sobre o outro e leiam.', 'presencial'),
  ('desafio', 'criativo', 'Façam um desfile temático com roupas dos dois misturadas.', 'presencial'),
  ('desafio', 'criativo', 'Inventem juntos uma receita de drink ou suco e deem um nome.', 'presencial'),
  ('desafio', 'criativo', 'Façam uma dancinha de rede social juntos.', 'presencial'),
  ('desafio', 'criativo', 'Criem um personagem com a voz do outro e façam ele dizer "eu te amo".', 'presencial'),
  ('desafio', 'criativo', 'Montem um mini cinema na sala com ingresso desenhado.', 'presencial'),
  ('desafio', 'criativo', 'Inventem uma história em que vocês são detetives procurando um beijo perdido.', 'presencial'),
  ('desafio', 'criativo', 'Desenhem a planta da casa dos sonhos de vocês, um cômodo cada.', 'presencial'),
  ('desafio', 'criativo', 'Façam uma escultura de toalha como em hotel.', 'presencial'),
  ('desafio', 'criativo', 'Escrevam juntos as regras do "país do casal".', 'presencial'),
  ('desafio', 'criativo', 'Façam um vídeo de stop motion de 10 fotos com objetos.', 'presencial'),
  ('desafio', 'criativo', 'Inventem o slogan do casal e escrevam num papel para pendurar.', 'presencial'),
  ('desafio', 'criativo', 'Criem uma trilha de bilhetes pela casa para o outro seguir.', 'presencial'),
  ('desafio', 'criativo', 'Encenem juntos o momento do reencontro, em câmera lenta.', 'presencial')
on conflict do nothing;

-- desafio presencial · picante (+54)
insert into public.cartas (tipo, nivel, texto, modo) values
  ('desafio', 'picante', 'Me beije como se a gente não se visse há um ano.', 'presencial'),
  ('desafio', 'picante', 'Passe a ponta dos dedos pelos meus lábios bem devagar.', 'presencial'),
  ('desafio', 'picante', 'Me abrace por trás e sussurre o que vai fazer mais tarde.', 'presencial'),
  ('desafio', 'picante', 'Desabotoe um botão da minha roupa a cada beijo.', 'presencial'),
  ('desafio', 'picante', 'Beije minha barriga devagar.', 'presencial'),
  ('desafio', 'picante', 'Me deite no seu colo e faça carinho na minha cintura.', 'presencial'),
  ('desafio', 'picante', 'Me dê um beijo de olhos vendados, sem eu saber onde vai ser.', 'presencial'),
  ('desafio', 'picante', 'Dance colado(a) comigo uma música lenta e provocante.', 'presencial'),
  ('desafio', 'picante', 'Morda de leve o meu lábio durante o beijo.', 'presencial'),
  ('desafio', 'picante', 'Tire minha meia ou sapato com toda a calma e beije meu pé ou tornozelo.', 'presencial'),
  ('desafio', 'picante', 'Me prense contra você e fiquem 10 segundos sem beijar.', 'presencial'),
  ('desafio', 'picante', 'Faça carinho na minha nuca enquanto me beija.', 'presencial'),
  ('desafio', 'picante', 'Me beije no pescoço até eu arrepiar.', 'presencial'),
  ('desafio', 'picante', 'Me sente na bancada ou na mesa e me beije.', 'presencial'),
  ('desafio', 'picante', 'Tire minha blusa só com uma mão.', 'presencial'),
  ('desafio', 'picante', 'Passe um cubo de gelo pelos meus ombros.', 'presencial'),
  ('desafio', 'picante', 'Sussurre no meu ouvido uma fantasia leve.', 'presencial'),
  ('desafio', 'picante', 'Me beije devagar do queixo até a orelha.', 'presencial'),
  ('desafio', 'picante', 'Me abrace na cama e faça carinho por baixo da blusa por 1 minuto.', 'presencial'),
  ('desafio', 'picante', 'Deite por cima de mim e me olhe sem beijar por 15 segundos.', 'presencial'),
  ('desafio', 'picante', 'Escolha uma peça minha para eu tirar agora.', 'presencial'),
  ('desafio', 'picante', 'Faça uma massagem na minha nuca com a boca.', 'presencial'),
  ('desafio', 'picante', 'Me beije enquanto segura meu rosto com firmeza.', 'presencial'),
  ('desafio', 'picante', 'Dance para mim tirando uma peça no fim.', 'presencial'),
  ('desafio', 'picante', 'Passe a mão pelo meu cabelo e puxe de leve para me beijar.', 'presencial'),
  ('desafio', 'picante', 'Me dê 10 beijos subindo pelo meu braço.', 'presencial'),
  ('desafio', 'picante', 'Fiquem só de roupa íntima por 1 rodada.', 'presencial'),
  ('desafio', 'picante', 'Me beije contra a parede por 20 segundos.', 'presencial'),
  ('desafio', 'picante', 'Desenhe com o dedo nas minhas costas e eu adivinho a palavra.', 'presencial'),
  ('desafio', 'picante', 'Passe chocolate ou mel no meu dedo e tire com a boca.', 'presencial'),
  ('desafio', 'picante', 'Me beije sem usar as mãos.', 'presencial'),
  ('desafio', 'picante', 'Sente no meu colo e me beije o pescoço.', 'presencial'),
  ('desafio', 'picante', 'Me deixe vendar seus olhos e te beijar onde eu quiser.', 'presencial'),
  ('desafio', 'picante', 'Me provoque com beijos e pare antes da boca, 3 vezes.', 'presencial'),
  ('desafio', 'picante', 'Tire minha camisa e beije meu ombro.', 'presencial'),
  ('desafio', 'picante', 'Me abrace por trás na frente do espelho e me olhe pelo reflexo.', 'presencial'),
  ('desafio', 'picante', 'Diga, me olhando nos olhos, o que mais quer fazer comigo hoje.', 'presencial'),
  ('desafio', 'picante', 'Me dê um beijo de 1 minuto cronometrado.', 'presencial'),
  ('desafio', 'picante', 'Faça carinho nas minhas coxas por 30 segundos, por cima da roupa.', 'presencial'),
  ('desafio', 'picante', 'Me deite na cama e me beije da testa ao pescoço.', 'presencial'),
  ('desafio', 'picante', 'Passe perfume em mim e cheire onde passou.', 'presencial'),
  ('desafio', 'picante', 'Me beije o pulso e suba até o ombro.', 'presencial'),
  ('desafio', 'picante', 'Me abrace bem forte e aperte minha cintura.', 'presencial'),
  ('desafio', 'picante', 'Escolha onde quer um chupão e me peça.', 'presencial'),
  ('desafio', 'picante', 'Me dê um beijo de esquimó que vira um beijo de verdade.', 'presencial'),
  ('desafio', 'picante', 'Sussurre meu nome no meu ouvido com a voz mais quente.', 'presencial'),
  ('desafio', 'picante', 'Massageie minhas costas por baixo da roupa por 2 minutos.', 'presencial'),
  ('desafio', 'picante', 'Me beije enquanto eu fico de olhos fechados e mãos para trás.', 'presencial'),
  ('desafio', 'picante', 'Faça uma pose sensual e me deixe te olhar por 10 segundos.', 'presencial'),
  ('desafio', 'picante', 'Me beije a orelha e diga uma palavra proibida.', 'presencial'),
  ('desafio', 'picante', 'Me tire para dançar e termine com um beijo no pescoço.', 'presencial'),
  ('desafio', 'picante', 'Fique atrás de mim e beije minhas costas descendo devagar.', 'presencial'),
  ('desafio', 'picante', 'Me prenda os pulsos com as mãos e me beije.', 'presencial'),
  ('desafio', 'picante', 'Troque de roupa na minha frente, bem devagar.', 'presencial')
on conflict do nothing;

-- desafio presencial · pesado (+52)
insert into public.cartas (tipo, nivel, texto, modo) values
  ('desafio', 'pesado', 'Tire minha roupa usando só a boca e os dentes.', 'presencial'),
  ('desafio', 'pesado', 'Escolham juntos uma posição do guia que nunca fizeram e testem.', 'presencial'),
  ('desafio', 'pesado', 'Me provoque por 3 minutos sem me deixar tocar em você.', 'presencial'),
  ('desafio', 'pesado', 'Tomem banho juntos e se ensaboem.', 'presencial'),
  ('desafio', 'pesado', 'Me vende e me surpreenda com 3 toques diferentes.', 'presencial'),
  ('desafio', 'pesado', 'Me deixe no comando por 5 minutos, com direito a veto.', 'presencial'),
  ('desafio', 'pesado', 'Me beije o corpo todo e pare só onde eu pedir.', 'presencial'),
  ('desafio', 'pesado', 'Façam uma posição escolhida por mim por 2 minutos.', 'presencial'),
  ('desafio', 'pesado', 'Use gelo e calor (bebida quente, respiração) no meu corpo.', 'presencial'),
  ('desafio', 'pesado', 'Me amarre os pulsos com algo macio e me provoque.', 'presencial'),
  ('desafio', 'pesado', 'Faça uma massagem com óleo e termine onde quiser.', 'presencial'),
  ('desafio', 'pesado', 'Escolha um cômodo da casa para a próxima rodada acontecer lá.', 'presencial'),
  ('desafio', 'pesado', 'Me diga o que quer e eu faço, com direito a veto.', 'presencial'),
  ('desafio', 'pesado', 'Faça em mim a fantasia que você contou na distância.', 'presencial'),
  ('desafio', 'pesado', 'Tire minha roupa e me olhe por 30 segundos sem tocar.', 'presencial'),
  ('desafio', 'pesado', 'Me provoque com a boca por 2 minutos.', 'presencial'),
  ('desafio', 'pesado', 'Troquem de posição a cada 30 segundos, por 3 minutos.', 'presencial'),
  ('desafio', 'pesado', 'Me leve para o chuveiro sem avisar.', 'presencial'),
  ('desafio', 'pesado', 'Me deixe escolher a posição e o ritmo.', 'presencial'),
  ('desafio', 'pesado', 'Cumpram agora o desafio Pesado que mais gostaram na distância.', 'presencial'),
  ('desafio', 'pesado', 'Façam juntos a fantasia que foi guardada num envelope.', 'presencial'),
  ('desafio', 'pesado', 'Me provoque até eu pedir, e só então continue.', 'presencial'),
  ('desafio', 'pesado', 'Escolha a parte do meu corpo que mais sentiu falta e se dedique a ela por 2 minutos.', 'presencial'),
  ('desafio', 'pesado', 'Me deixe vendado(a) e mude de lugar comigo pela casa.', 'presencial'),
  ('desafio', 'pesado', 'Façam uma posição em pé.', 'presencial'),
  ('desafio', 'pesado', 'Me deite e faça o que quiser por 3 minutos, com direito a veto.', 'presencial'),
  ('desafio', 'pesado', 'Use uma peça de roupa minha para me amarrar ou vendar.', 'presencial'),
  ('desafio', 'pesado', 'Escolham a posição mais ousada do cardápio e façam agora.', 'presencial'),
  ('desafio', 'pesado', 'Me mostre com o corpo o que você queria me mostrar pela câmera.', 'presencial'),
  ('desafio', 'pesado', 'Me beije em todos os lugares que eu apontar, sem pular nenhum.', 'presencial'),
  ('desafio', 'pesado', 'Façam de olhos vendados os dois.', 'presencial'),
  ('desafio', 'pesado', 'Me deixe te despir peça por peça, sem você ajudar.', 'presencial'),
  ('desafio', 'pesado', 'Escolha um ritmo e não mude até o cronômetro acabar.', 'presencial'),
  ('desafio', 'pesado', 'Façam na frente do espelho.', 'presencial'),
  ('desafio', 'pesado', 'Me provoque sussurrando o que vai fazer antes de fazer.', 'presencial'),
  ('desafio', 'pesado', 'Tire a minha roupa íntima com os dentes.', 'presencial'),
  ('desafio', 'pesado', 'Me deite de bruços e me beije das costas até as pernas.', 'presencial'),
  ('desafio', 'pesado', 'Escolham uma posição para cada letra do nome do casal.', 'presencial'),
  ('desafio', 'pesado', 'Me amarre e me provoque até eu implorar.', 'presencial'),
  ('desafio', 'pesado', 'Faça um striptease completo e me puxe para a cama.', 'presencial'),
  ('desafio', 'pesado', 'Me deixe escolher o cômodo e a posição.', 'presencial'),
  ('desafio', 'pesado', 'Façam a posição que foi a primeira escolha do cardápio do reencontro.', 'presencial'),
  ('desafio', 'pesado', 'Me provoque com a ponta da língua por 1 minuto.', 'presencial'),
  ('desafio', 'pesado', 'Me use como apoio para a posição que quiser.', 'presencial'),
  ('desafio', 'pesado', 'Façam devagar por 2 minutos sem acelerar.', 'presencial'),
  ('desafio', 'pesado', 'Me deixe no controle total da próxima rodada, com direito a veto.', 'presencial'),
  ('desafio', 'pesado', 'Experimentem um lugar da casa que nunca usaram.', 'presencial'),
  ('desafio', 'pesado', 'Me dê ordens ousadas por 2 minutos e eu obedeço, com direito a veto.', 'presencial'),
  ('desafio', 'pesado', 'Me prenda contra a parede e faça o que quiser.', 'presencial'),
  ('desafio', 'pesado', 'Me peça a coisa mais ousada que pensou na distância e eu decido se cumpro.', 'presencial'),
  ('desafio', 'pesado', 'Escolham uma posição e troquem quem conduz no meio.', 'presencial'),
  ('desafio', 'pesado', 'Façam até o cronômetro de 5 minutos acabar sem parar.', 'presencial')
on conflict do nothing;

-- prenda presencial · romantico (+13)
insert into public.cartas (tipo, nivel, texto, modo) values
  ('prenda', 'romantico', 'Me dê um beijo para cada dedo da minha mão.', 'presencial'),
  ('prenda', 'romantico', 'Diga "eu te amo" em 3 idiomas, me abraçando.', 'presencial'),
  ('prenda', 'romantico', 'Me faça um carinho no rosto por 30 segundos.', 'presencial'),
  ('prenda', 'romantico', 'Me carregue no colo até o sofá (ou tente).', 'presencial'),
  ('prenda', 'romantico', 'Me conte uma lembrança nossa me olhando nos olhos.', 'presencial'),
  ('prenda', 'romantico', 'Faça um coração com as mãos e me beije através dele.', 'presencial'),
  ('prenda', 'romantico', 'Cante o refrão da nossa música no meu ouvido.', 'presencial'),
  ('prenda', 'romantico', 'Me faça um chá, café ou suco com carinho.', 'presencial'),
  ('prenda', 'romantico', 'Me abrace por trás até eu dizer chega.', 'presencial'),
  ('prenda', 'romantico', 'Me dê um selinho a cada 10 segundos, por 1 minuto.', 'presencial'),
  ('prenda', 'romantico', 'Escreva um bilhete fofo e cole em mim.', 'presencial'),
  ('prenda', 'romantico', 'Faça massagem nos meus pés por 1 minuto.', 'presencial'),
  ('prenda', 'romantico', 'Me chame de um apelido carinhoso até o fim da noite.', 'presencial')
on conflict do nothing;

-- prenda presencial · leve (+13)
insert into public.cartas (tipo, nivel, texto, modo) values
  ('prenda', 'leve', 'Faça 10 agachamentos me dando um beijo em cada.', 'presencial'),
  ('prenda', 'leve', 'Imite uma galinha por 10 segundos.', 'presencial'),
  ('prenda', 'leve', 'Dance sem música por 15 segundos.', 'presencial'),
  ('prenda', 'leve', 'Fale com voz de robô até a próxima rodada.', 'presencial'),
  ('prenda', 'leve', 'Me leve um copo de água correndo.', 'presencial'),
  ('prenda', 'leve', 'Deixe eu desenhar um bigode em você com caneta.', 'presencial'),
  ('prenda', 'leve', 'Faça 5 flexões (ou tente).', 'presencial'),
  ('prenda', 'leve', 'Use uma peça de roupa minha até o fim da rodada.', 'presencial'),
  ('prenda', 'leve', 'Conte uma piada ruim e ria dela sozinho(a).', 'presencial'),
  ('prenda', 'leve', 'Ande de costas até a cozinha e volte.', 'presencial'),
  ('prenda', 'leve', 'Faça uma careta e deixe eu tirar foto.', 'presencial'),
  ('prenda', 'leve', 'Me deixe escolher seu penteado.', 'presencial'),
  ('prenda', 'leve', 'Fique em silêncio até a próxima rodada.', 'presencial')
on conflict do nothing;

-- prenda presencial · criativo (+12)
insert into public.cartas (tipo, nivel, texto, modo) values
  ('prenda', 'criativo', 'Faça uma estátua engraçada até eu rir.', 'presencial'),
  ('prenda', 'criativo', 'Cante uma música trocando a letra por algo sobre mim.', 'presencial'),
  ('prenda', 'criativo', 'Desenhe um retrato meu em 20 segundos.', 'presencial'),
  ('prenda', 'criativo', 'Faça uma propaganda de você mesmo(a).', 'presencial'),
  ('prenda', 'criativo', 'Imite um personagem que eu escolher por 30 segundos.', 'presencial'),
  ('prenda', 'criativo', 'Invente um poema de 2 versos rimando com o meu nome.', 'presencial'),
  ('prenda', 'criativo', 'Dance como um robô até a próxima carta.', 'presencial'),
  ('prenda', 'criativo', 'Faça um discurso de 20 segundos sobre por que eu sou incrível.', 'presencial'),
  ('prenda', 'criativo', 'Conte uma história usando 3 objetos que eu apontar.', 'presencial'),
  ('prenda', 'criativo', 'Faça teatro de sombras com uma lanterna.', 'presencial'),
  ('prenda', 'criativo', 'Monte uma coroa de papel e use até o fim da rodada.', 'presencial'),
  ('prenda', 'criativo', 'Narre o que estou fazendo como narrador de futebol.', 'presencial')
on conflict do nothing;

-- prenda presencial · picante (+12)
insert into public.cartas (tipo, nivel, texto, modo) values
  ('prenda', 'picante', 'Me beije no pescoço até eu pedir para parar.', 'presencial'),
  ('prenda', 'picante', 'Tire uma peça de roupa na minha frente.', 'presencial'),
  ('prenda', 'picante', 'Faça uma massagem nas minhas costas por 1 minuto.', 'presencial'),
  ('prenda', 'picante', 'Me deixe escolher onde você vai me beijar.', 'presencial'),
  ('prenda', 'picante', 'Sussurre no meu ouvido a coisa mais ousada que pensou hoje.', 'presencial'),
  ('prenda', 'picante', 'Dance colado(a) comigo por 30 segundos.', 'presencial'),
  ('prenda', 'picante', 'Fique sem blusa até a próxima rodada.', 'presencial'),
  ('prenda', 'picante', 'Me beije de olhos fechados por 20 segundos.', 'presencial'),
  ('prenda', 'picante', 'Morda de leve a minha orelha.', 'presencial'),
  ('prenda', 'picante', 'Me provoque com beijos sem chegar na boca.', 'presencial'),
  ('prenda', 'picante', 'Faça uma pose provocante para mim.', 'presencial'),
  ('prenda', 'picante', 'Me dê um beijo de 30 segundos.', 'presencial')
on conflict do nothing;

-- prenda presencial · pesado (+11)
insert into public.cartas (tipo, nivel, texto, modo) values
  ('prenda', 'pesado', 'Tire tudo e fique assim até a próxima rodada.', 'presencial'),
  ('prenda', 'pesado', 'Me deixe vendar seus olhos na próxima carta.', 'presencial'),
  ('prenda', 'pesado', 'Faça o que eu pedir por 2 minutos, com direito a veto.', 'presencial'),
  ('prenda', 'pesado', 'Tome banho comigo agora.', 'presencial'),
  ('prenda', 'pesado', 'Me deixe escolher a próxima posição.', 'presencial'),
  ('prenda', 'pesado', 'Me provoque por 1 minuto só com a boca.', 'presencial'),
  ('prenda', 'pesado', 'Fique sem roupa íntima até o fim da noite.', 'presencial'),
  ('prenda', 'pesado', 'Me deixe amarrar seus pulsos com algo macio por 2 minutos.', 'presencial'),
  ('prenda', 'pesado', 'Me dê o comando da próxima rodada.', 'presencial'),
  ('prenda', 'pesado', 'Faça um striptease para mim.', 'presencial'),
  ('prenda', 'pesado', 'Me beije onde eu escolher por 30 segundos.', 'presencial')
on conflict do nothing;

-- Conferência: cada linha precisa ter longe = perto
select tipo, nivel,
       count(*) filter (where modo = 'distancia')  as longe,
       count(*) filter (where modo = 'presencial') as perto,
       count(*) filter (where modo = 'ambos')      as ambos
from public.cartas
where sala is null and tipo in ('verdade','desafio','prenda')
group by 1, 2 order by 1, 2;
