// Banco de verdades e desafios. Para adicionar, é só incluir uma linha na lista do nível.
window.VERDADES = {
  leve: [
    "Qual foi a primeira coisa que você reparou em mim?",
    "Qual momento nosso você reviveria se pudesse?",
    "O que você faz quando está com saudade de mim?",
    "Qual mania minha você acha mais fofa?",
    "Qual mania minha te irrita um pouquinho?",
    "Qual mensagem minha mais te marcou até hoje?",
    "Se a gente tivesse um dia juntos amanhã, o que faríamos?",
    "Qual música te faz pensar em mim?",
    "Qual foi a vez que você mais sentiu ciúme de mim?",
    "O que você ainda não me contou sobre a sua infância?",
    "Qual apelido meu você mais gosta?",
    "Qual foi o seu maior mico na frente de alguém que você gostava?",
    "Qual lugar você mais quer conhecer comigo?",
    "Em que momento você percebeu que gostava de mim?",
    "Qual comida você quer que a gente coma junto no reencontro?",
    "Qual foi o dia mais difícil da distância para você?",
    "Qual defeito seu você acha que eu nem percebi?",
    "Como você imagina a nossa vida daqui a 5 anos?",
    "Qual foi a última vez que você chorou, e por quê?",
    "O que eu faço que te deixa com o dia melhor?"
  ],
  criativo: [
    "Se o nosso namoro fosse um filme, qual seria o título?",
    "Se eu fosse um animal, qual eu seria, e por quê?",
    "Que superpoder você usaria para chegar até mim agora?",
    "Descreva o nosso casal usando só 3 emojis.",
    "Se a gente tivesse uma banda, qual seria o nome e o estilo?",
    "Qual personagem de série mais parece comigo?"
  ],
  picante: [
    "Em que momento você mais sentiu vontade de me beijar?",
    "O que em mim mais te provoca?",
    "Qual roupa minha você mais gosta de me ver usando?",
    "Já pensou em mim num momento totalmente inapropriado? Qual?",
    "Onde você mais gostaria de me beijar agora?",
    "Qual foi o nosso momento mais quente até hoje?",
    "Qual mensagem minha mais te deixou mexido(a)?",
    "Qual parte do reencontro você mais imagina?",
    "O que você gostaria que eu fizesse mais vezes?",
    "Qual é a sua fantasia mais leve comigo?"
  ],
  pesado: [
    "Qual fantasia você tem vergonha de me contar?",
    "Qual foi o pensamento mais ousado que você já teve comigo?",
    "O que você nunca fez e gostaria de experimentar comigo?",
    "Qual limite seu eu ainda não conheço?",
    "Como seria o nosso reencontro, sem cortes?"
  ]
};

window.DESAFIOS = {
  leve: [
    "Faça 10 polichinelos cantando a nossa música.",
    "Desenhe meu retrato em 60 segundos e mostre na câmera.",
    "Imite meu jeito de falar quando acabo de acordar.",
    "Invente uma história de 1 minuto usando 3 objetos que estão perto de você.",
    "Dance por 15 segundos a música que eu escolher.",
    "Faça um desfile de moda com 3 peças aleatórias do seu guarda-roupa.",
    "Monte um look usando só coisas da cozinha.",
    "Imite um apresentador de jornal anunciando uma notícia sobre nós dois.",
    "Faça a pior careta que conseguir e segure 10 segundos sem rir.",
    "Cante o refrão de uma música trocando a letra por palavras sobre mim.",
    "Faça a pose de estátua que eu escolher e fique parado(a) 30 segundos.",
    "Desenhe o nosso próximo encontro em 2 minutos.",
    "Mostre o objeto mais estranho do seu quarto e invente a história dele.",
    "Leia algo que estiver perto de você com voz de narrador de novela.",
    "Faça um comercial de 30 segundos vendendo um item do seu quarto.",
    "Imite um animal até eu adivinhar qual é.",
    "Faça mímica de um filme até eu acertar.",
    "Escreva um poema de 4 versos sobre mim em 2 minutos e leia.",
    "Faça 10 agachamentos mandando um beijo a cada um.",
    "Equilibre um objeto na cabeça e atravesse o cômodo.",
    "Fale por 1 minuto sobre o seu dia sem dizer a palavra \"não\".",
    "Desenhe com a mão não dominante o bicho que eu escolher.",
    "Faça um tour pelo seu quarto como se fosse guia de museu.",
    "Imite um professor dando uma aula sobre mim.",
    "Faça beatbox por 20 segundos.",
    "Conte a piada mais ruim que souber com a cara totalmente séria.",
    "Faça um penteado maluco em 1 minuto.",
    "Crie um personagem com o que tiver no quarto e fale como ele por 1 minuto.",
    "Vamos criar um aperto de mão secreto nosso pela câmera.",
    "Faça sua melhor pose de capa de revista (eu tiro print).",
    "Faça um aviãozinho de papel e lance o mais longe que conseguir.",
    "Escreva meu nome no ar usando o corpo inteiro.",
    "Recrie um meme famoso.",
    "Recrie a nossa primeira foto juntos, só que sozinho(a).",
    "Diga 5 coisas que você ama em mim em 20 segundos.",
    "Fale com o sotaque de outro estado pelas próximas 2 rodadas.",
    "Duble uma cena de filme que eu colocar sem som.",
    "Desenhe como você imagina a nossa casa no futuro.",
    "Faça prancha por 30 segundos enquanto responde uma pergunta minha.",
    "Imite uma celebridade até eu adivinhar quem é.",
    "Ache em 30 segundos um objeto de cada cor que eu disser.",
    "Toque uma música com um instrumento improvisado (panela, copo, caneta).",
    "Faça um rap de 4 versos sobre o seu dia.",
    "Narre o que vai fazer amanhã como narrador de futebol.",
    "Escreva uma carta de amor de 3 linhas como se estivéssemos em 1800.",
    "Responda as próximas 3 perguntas só cantando.",
    "Desenhe um mapa do tesouro da sua casa e explique onde está o tesouro.",
    "Adivinhe 3 coisas que estão na minha mesa agora.",
    "Faça uma declaração de amor dramática estilo novela mexicana.",
    "Mande uma selfie agora, do jeito que você estiver, sem se arrumar."
  ],
  criativo: [
    "Invente o trailer de 1 minuto de um filme sobre nós dois.",
    "Crie um nome e um logo para o nosso casal e desenhe.",
    "Narre como seria o nosso encontro perfeito no estilo documentário de natureza.",
    "Escreva uma música de 4 versos na melodia de \"Parabéns a você\".",
    "Invente uma receita com 3 ingredientes da sua geladeira e apresente como chef de TV.",
    "Me desenhe como herói ou heroína de desenho animado.",
    "Crie uma coreografia de 20 segundos que eu tenho que copiar.",
    "Faça teatro de sombras com as mãos e conte uma história curta.",
    "Invente uma palavra nova e diga o que ela significa para nós.",
    "Escreva um haicai (3 versos curtos) sobre saudade.",
    "Me entreviste como se eu fosse uma pessoa famosa.",
    "Monte uma cena com objetos da casa e narre o que está acontecendo.",
    "Recrie a capa de um álbum ou filme famoso usando coisas de casa.",
    "Imite como eu fico quando estou com fome.",
    "Invente o meu horóscopo de hoje.",
    "História a dois: cada um fala uma frase, por 10 rodadas.",
    "Desenhe de olhos fechados o que eu descrever.",
    "Faça um unboxing dramático de um objeto qualquer.",
    "Faça um cartaz de procura-se com meu retrato falado e uma recompensa.",
    "Apresente o nosso próximo encontro em 1 minuto como se fosse agente de viagens.",
    "Treino juntos: 1 minuto de exercícios que eu vou comandando.",
    "Espelho: imite todos os meus movimentos por 30 segundos.",
    "Fique numa perna só de olhos fechados o máximo que conseguir.",
    "Faça 3 posições de ioga que eu escolher.",
    "Pedra, papel e tesoura, melhor de 5: quem perde cumpre um desafio extra.",
    "Tente encostar a língua no nariz.",
    "Monte a torre mais alta que conseguir com objetos em 1 minuto.",
    "Corrida: traga primeiro para a câmera o objeto que eu disser.",
    "Encene uma cena de filme romântico sozinho(a), fazendo as duas vozes.",
    "Desenhe um presente que você gostaria de me dar."
  ],
  picante: [
    "Diga sussurrando o que você faria se eu estivesse aí agora.",
    "Mande um áudio de 20 segundos com a sua voz mais sedutora.",
    "Faça uma dança sensual de 20 segundos na música que eu escolher.",
    "Descreva o nosso melhor beijo com detalhes.",
    "Mostre a peça de roupa que você acha que mais me provoca.",
    "Tire uma foto sensual (você decide o nível) e mande em visualização única.",
    "Conte uma fantasia leve que você nunca me contou.",
    "Beije a câmera como se fosse eu.",
    "Faça um desfile com a roupa que eu escolher.",
    "Diga as 3 partes de mim que você mais gosta.",
    "Morda o lábio e me olhe fixo por 10 segundos sem rir.",
    "Escreva e leia em voz alta uma mensagem picante de 3 linhas.",
    "Tire uma peça de roupa (acessório também conta).",
    "Descreva em detalhes como vai ser o nosso reencontro.",
    "Massageie o próprio pescoço narrando como se fossem as minhas mãos."
  ],
  pesado: [
    "Tire uma peça de roupa bem devagar, na música que eu escolher.",
    "Conte em detalhes a sua fantasia mais ousada comigo.",
    "Mande uma foto ousada (o limite é seu), em visualização única.",
    "Eu escolho o que você vai vestir pelo resto da chamada.",
    "Siga as minhas instruções por 2 minutos, com direito a vetar qualquer uma."
  ]
};

window.LEVEL_NAMES = {leve:"Leve", criativo:"Criativo", picante:"Picante", pesado:"Pesado +18"};
